/**
 * THE LAYER SMEAR MODEL — asserted, not admired.
 * Plan of record: `docs/planning/Sun-Shadows-Layer-Smear.md`.
 *
 * The load-bearing test in this file is THE LAW: *"We cannot have a shadow which
 * is generated by opaque occluders which ever goes from black to grey to white
 * to grey to white"* (author, 2026-08-02). Two previous shadow models each
 * shipped a violation of it that looked plausible on screen — a bright halo
 * hugging every building, and a detached second shadow further out — so it is
 * pinned here across many silhouettes, sun angles and step counts rather than
 * argued for in a comment.
 *
 * The model's monotonicity PROOF (see `layer-smear.js`'s header) consumes
 * exactly one property: that the falloff decreases. That single precondition
 * gets its own test first, because if it ever stops holding, every other
 * guarantee in this file evaporates silently.
 */
import {
  SHADOW_LAYER_COUNT,
  LAYER_WALLS,
  LAYER_OVERHEAD,
  SHADOW_BAND_LAYER_INDICES,
  DIFFUSION_PER_HEIGHT_PX,
  layerThrowPx,
  layerDiffusionBlurPx,
  smearFalloff01,
  stationDistancePx,
  stationSpacingPx,
  resolveLayerSmear,
  layerSmearVisibility,
} from '../layer-smear.js';
import { marchDirectionToSun } from '../sun-occlusion.js';

const near = (a, b, eps = 1e-6) => Math.abs(a - b) < eps;

/** @param {{ok:(name:string, cond:boolean)=>void}} t */
export function run(t) {
  // ── THE FALLOFF — THE LAW'S ONE PRECONDITION ─────────────────────────
  {
    let strictlyDecreasing = true;
    for (const e of [0.5, 1, 1.6, 2.5, 4]) {
      let prev = Infinity;
      for (let i = 0; i <= 200; i++) {
        const v = smearFalloff01(i / 200, e);
        if (v > prev + 1e-12) strictlyDecreasing = false;
        prev = v;
      }
    }
    t.ok('the falloff decreases monotonically on [0,1] for every exponent — THE LAW rests on this', strictlyDecreasing);
    t.ok('fully dark against its caster', near(smearFalloff01(0, 1.6), 1));
    t.ok('exactly gone at the throw distance — no hard tip', near(smearFalloff01(1, 1.6), 0));
    t.ok('past the throw distance stays gone', smearFalloff01(1.5, 1.6) === 0 && smearFalloff01(9, 1.6) === 0);
  }

  // ── THROW LENGTH ─────────────────────────────────────────────────────
  {
    t.ok('a 100px layer at 45° throws 100px', near(layerThrowPx({ heightPx: 100, elevationDeg: 45 }), 100, 1e-9));
    t.ok(
      'the same layer reaches further as the sun lowers',
      layerThrowPx({ heightPx: 100, elevationDeg: 20 }) > layerThrowPx({ heightPx: 100, elevationDeg: 60 })
    );
    t.ok('a sun overhead throws nothing', near(layerThrowPx({ heightPx: 100, elevationDeg: 90 }), 0, 1e-6));
    t.ok('a zero-height layer throws nothing', layerThrowPx({ heightPx: 0, elevationDeg: 10 }) === 0);
    const grazing = layerThrowPx({ heightPx: 100, elevationDeg: 0 });
    t.ok(
      'a sun ON the horizon saturates at a cap — never Infinity, never NaN',
      Number.isFinite(grazing) && grazing > 0
    );
    t.ok(
      'lengthScale shortens every shadow',
      layerThrowPx({ heightPx: 200, elevationDeg: 30, lengthScale: 0.5 }) <
        layerThrowPx({ heightPx: 200, elevationDeg: 30 })
    );
    t.ok(
      'maxLengthMul caps the dawn blow-up but leaves midday alone',
      layerThrowPx({ heightPx: 100, elevationDeg: 5, maxLengthMul: 3 }) <= 300 + 1e-6 &&
        near(layerThrowPx({ heightPx: 100, elevationDeg: 45, maxLengthMul: 3 }), 100, 1e-6)
    );
  }

  // ── STATION LADDER ───────────────────────────────────────────────────
  {
    const n = 32;
    const L = 640;
    t.ok('station 0 is the receiver itself', stationDistancePx(0, n, L) === 0);
    t.ok('the last station lands exactly on the throw distance', near(stationDistancePx(n, n, L), L, 1e-9));
    let increasing = true;
    for (let j = 1; j <= n; j++) {
      if (stationDistancePx(j, n, L) <= stationDistancePx(j - 1, n, L)) increasing = false;
    }
    t.ok('stations advance strictly outward', increasing);
    t.ok(
      'stations bunch toward the caster — the first gap is far smaller than the last',
      stationDistancePx(1, n, L) - stationDistancePx(0, n, L) <
        (stationDistancePx(n, n, L) - stationDistancePx(n - 1, n, L)) / 10
    );
    // The spacing helper is the shader's anti-aliasing floor; if it under-reports
    // the true gap, a thin caster can hide between two stations and THE LAW
    // breaks discretely (memory: feedback_narrow_tolerance_between_march_samples).
    let coversEveryGap = true;
    for (let j = 1; j <= n; j++) {
      const trueGap = stationDistancePx(j, n, L) - stationDistancePx(j - 1, n, L);
      if (stationSpacingPx(j, n, L) < trueGap - 1e-9) coversEveryGap = false;
    }
    t.ok('the reported station spacing is never NARROWER than the real gap it must cover', coversEveryGap);
  }

  // ══════════════════════════════════════════════════════════════════════
  // ⚖️ THE LAW — a shadow may only ever get lighter with distance
  // ══════════════════════════════════════════════════════════════════════
  {
    /** Build a `sampleLayers` over a set of axis-aligned rectangles, one per
     * layer. Clamp-to-edge is irrelevant here (nothing runs off), so this is a
     * plain point test. */
    const rects = (specs) => (x, y) =>
      specs.map((r) => (r && x >= r.x0 && x <= r.x1 && y >= r.y0 && y <= r.y1 ? 1 : 0));

    const CX = 2000;
    const CY = 2000;
    const box = (half) => ({ x0: CX - half, x1: CX + half, y0: CY - half, y1: CY + half });
    // A profile must start OUTSIDE the caster's own footprint, never inside
    // it. ⚠️ `BOX_HALF * Math.SQRT2`, NOT `BOX_HALF` — a square's DIAGONAL
    // half-extent is wider than its edge-on one (the identical trap this
    // file's own self-footprint block documents for the "beside" probe
    // below). Before walls had a self-exclusion (2026-08-03) this never
    // mattered: standing ON the wall and standing freshly IN its cast
    // shadow were both undiscounted, equally-darkest — so a profile that
    // technically started mid-caster still read as monotonically
    // lightening by accident. Now that a wall's own top is correctly LIT
    // (the roof-ridge fix), a profile starting mid-caster sees light (on
    // the wall) fall to black (stepping off its edge into full contact-
    // hard shadow) — a real cliff, but not a THE-LAW violation: THE LAW
    // governs a receiver OUTSIDE a caster, not the relationship between a
    // caster's own top and the ground beside it. The sweep must start past
    // the box entirely, for every tested azimuth, or it is measuring that
    // cliff instead of the thing it means to measure.
    const BOX_HALF = 300;
    const START_OUTSIDE_BOX = Math.ceil(BOX_HALF * Math.SQRT2) + 10;

    /** Walk outward from the caster along the direction a shadow is THROWN and
     * return the visibility profile. */
    const profile = (sampleLayers, heightsPx, azimuthDeg, elevationDeg, steps, startPx, endPx, n = 120) => {
      const toSun = marchDirectionToSun(azimuthDeg);
      const shadowDir = { x: -toSun.x, y: -toSun.y };
      const resolved = resolveLayerSmear({ azimuthDeg, elevationDeg, heightsPx });
      const out = [];
      for (let i = 0; i <= n; i++) {
        const d = startPx + ((endPx - startPx) * i) / n;
        out.push({
          d,
          v: layerSmearVisibility({
            x: CX + shadowDir.x * d,
            y: CY + shadowDir.y * d,
            sampleLayers,
            resolved,
            steps,
          }),
        });
      }
      return out;
    };

    /** The worst RISE in occlusion (= drop in visibility) anywhere in a profile.
     * A tiny tolerance absorbs float noise; anything above it is a real
     * black→grey→BLACK curve, which is what the author is looking at. */
    const worstDrop = (prof) => {
      let worst = 0;
      let at = null;
      for (let i = 1; i < prof.length; i++) {
        const drop = prof[i - 1].v - prof[i].v;
        if (drop > worst) {
          worst = drop;
          at = prof[i].d;
        }
      }
      return { worst, at };
    };

    // ── One wall, swept across the whole sky ────────────────────────────
    {
      const sample = rects([box(300), null, null, null]);
      let worstEver = 0;
      let worstCase = null;
      for (const az of [0, 37, 90, 143, 180, 220, 270, 315]) {
        for (const el of [8, 20, 35, 55, 75]) {
          for (const steps of [16, 32, 64]) {
            const p = profile(sample, [400, 0, 0, 0], az, el, steps, START_OUTSIDE_BOX, 2200);
            const { worst, at } = worstDrop(p);
            if (worst > worstEver) {
              worstEver = worst;
              worstCase = { az, el, steps, at };
            }
          }
        }
      }
      t.ok(
        `a single wall NEVER darkens with distance, across 8 azimuths x 5 elevations x 3 step counts ` +
          `(worst rise ${worstEver.toFixed(4)}${worstCase ? ` at ${JSON.stringify(worstCase)}` : ''})`,
        worstEver < 0.02
      );
    }

    // ⚠️ THE SINGLE-WALL SWEEP ABOVE CANNOT CATCH A BAD FALLOFF, and knowing
    // that is what makes the next block load-bearing rather than decorative.
    // Sabotage-tested 2026-08-02 with a deliberately non-monotonic `f`: the
    // wall sweep still PASSED. For one convex occluder, `occ(x) = max over
    // d ≥ x of f(d/L)` — a max over an interval that only ever SHRINKS as the
    // receiver moves away, and a max over a shrinking interval is non-increasing
    // whatever shape `f` has. The `max` hides the defect. Only DISJOINT,
    // staggered occluders let the argmax jump between features and expose it,
    // which the four-layer sweep below does and which is also the exact shape
    // that produced the author's detached "second shadow".
    //
    // ── The full four-layer stack, which is where the previous model broke ──
    // A wall, an overhead slab offset one way, and two upper floors offset
    // another — deliberately staggered so their throws end at different
    // distances. That staggering is EXACTLY the shape that produced the
    // author's detached "second shadow" under a shared mean.
    {
      const sample = rects([
        box(300),
        { x0: CX - 700, x1: CX + 100, y0: CY - 200, y1: CY + 600 },
        { x0: CX - 200, x1: CX + 900, y0: CY - 900, y1: CY + 200 },
        { x0: CX - 1100, x1: CX + 400, y0: CY - 400, y1: CY + 1100 },
      ]);
      const heights = [300, 500, 900, 1400];
      let worstEver = 0;
      let worstCase = null;
      for (const az of [0, 45, 110, 180, 220, 300]) {
        for (const el of [10, 25, 45, 70]) {
          const p = profile(sample, heights, az, el, 48, 320, 4000, 200);
          const { worst, at } = worstDrop(p);
          if (worst > worstEver) {
            worstEver = worst;
            worstCase = { az, el, at };
          }
        }
      }
      t.ok(
        `a FOUR-LAYER stack with staggered throws never darkens with distance ` +
          `(worst rise ${worstEver.toFixed(4)}${worstCase ? ` at ${JSON.stringify(worstCase)}` : ''})`,
        worstEver < 0.02
      );
    }

    // ── Guard the guard: the sweeps above must actually see shadow ───────
    // A profile that is fully lit everywhere satisfies "never darkens"
    // vacuously, and would have passed on a model that cast nothing at all
    // (memory: feedback_instruments_must_not_lie).
    {
      const sample = rects([box(300), null, null, null]);
      const p = profile(sample, [400, 0, 0, 0], 220, 30, 32, START_OUTSIDE_BOX, 2200);
      const darkest = Math.min(...p.map((r) => r.v));
      const lightest = Math.max(...p.map((r) => r.v));
      t.ok('THE LAW sweep is not vacuous: it passes through real shadow', darkest < 0.35);
      t.ok('THE LAW sweep is not vacuous: it also reaches real light', lightest > 0.9);
    }

    // ── DARKEST AGAINST THE CASTER — the author's stated requirement ─────
    {
      const sample = rects([box(300), null, null, null]);
      const p = profile(sample, [400, 0, 0, 0], 220, 30, 48, START_OUTSIDE_BOX, 800, 60);
      t.ok('the shadow is at its darkest right against the wall', p[0].v === Math.min(...p.map((r) => r.v)));
    }

    // ── COMPOUNDING — a second occluder never lightens ───────────────────
    // The regression guard carried over from the previous model, where a shared
    // softmax mean measurably let a WEAK second shadow LIGHTEN a strong first
    // (memory: feedback_mean_cannot_compound_occluders).
    {
      const wall = box(300);
      const slab = { x0: CX - 700, x1: CX + 200, y0: CY - 300, y1: CY + 700 };
      const both = rects([wall, slab, null, null]);
      const wallOnly = rects([wall, null, null, null]);
      const slabOnly = rects([null, slab, null, null]);
      const heights = [300, 700, 0, 0];
      const toSun = marchDirectionToSun(220);
      const shadowDir = { x: -toSun.x, y: -toSun.y };
      const resolved = resolveLayerSmear({ azimuthDeg: 220, elevationDeg: 30, heightsPx: heights });
      const at = (sampleLayers, d) =>
        layerSmearVisibility({
          x: CX + shadowDir.x * d,
          y: CY + shadowDir.y * d,
          sampleLayers,
          resolved,
          steps: 48,
        });
      let everLighter = null;
      let sawBothActive = false;
      for (let d = 305; d <= 1600; d += 25) {
        const vb = at(both, d);
        const vw = at(wallOnly, d);
        const vs = at(slabOnly, d);
        if (vw < 0.98 && vs < 0.98) sawBothActive = true;
        if (vb > Math.min(vw, vs) + 1e-6)
          everLighter = { d, vb: +vb.toFixed(3), vw: +vw.toFixed(3), vs: +vs.toFixed(3) };
      }
      t.ok('compounding guard is not vacuous: some probe has BOTH layers casting', sawBothActive);
      t.ok('a second layer never lightens: both together is at least as dark as either alone', everLighter === null);
    }

    // ── THE EDGE RULE — a building running off the map keeps casting ─────
    // Author: *"If the black pixels of _Outdoors extend across the edge of the
    // map then we assume that this continues into the distance."* Modelled the
    // way the sampler models it: clamp the read to the rect.
    {
      const RECT = { minX: 0, minY: 0, maxX: 4000, maxY: 4000 };
      // A wall hard against the map's minX border, and NOTHING beyond it.
      const clamped = (x, y) => {
        const cx = Math.min(RECT.maxX, Math.max(RECT.minX, x));
        const cy = Math.min(RECT.maxY, Math.max(RECT.minY, y));
        return [cx <= 200 && cy >= 1500 && cy <= 2500 ? 1 : 0, 0, 0, 0];
      };
      // Sun in the −x direction (azimuth 270 walks the back-trace to −x), so a
      // receiver to the +x side of the border wall is in its shadow, and the
      // back-trace runs OFF the map.
      const resolved = resolveLayerSmear({ azimuthDeg: 270, elevationDeg: 30, heightsPx: [500, 0, 0, 0] });
      const onMap = layerSmearVisibility({ x: 260, y: 2000, sampleLayers: clamped, resolved, steps: 48 });
      t.ok('a wall on the map border still casts into the map', onMap < 0.6);
      // And the clamp must not invent a caster where the border is CLEAR.
      const clearBorder = () => [0, 0, 0, 0];
      const noCaster = layerSmearVisibility({ x: 260, y: 2000, sampleLayers: clearBorder, resolved, steps: 48 });
      t.ok('a clear border invents no shadow — clamping extends content, it does not create it', near(noCaster, 1));
    }

    // ── BOUNDS AND SWITCHES ──────────────────────────────────────────────
    {
      const sample = rects([box(300), null, null, null]);
      const resolved = resolveLayerSmear({ azimuthDeg: 220, elevationDeg: 30, heightsPx: [400, 0, 0, 0] });
      const toSun = marchDirectionToSun(220);
      const p = { x: CX - toSun.x * 400, y: CY - toSun.y * 400 };
      t.ok(
        'a closed receiver gate returns fully lit regardless of geometry',
        layerSmearVisibility({ ...p, sampleLayers: sample, resolved, steps: 32, receiverGate: 0 }) === 1
      );
      t.ok(
        'strength 0 returns exactly 1 however many layers are stacked',
        near(layerSmearVisibility({ ...p, sampleLayers: sample, resolved, steps: 32, strength: 0 }), 1)
      );
      t.ok(
        'a per-layer strength of 0 removes that layer entirely',
        near(layerSmearVisibility({ ...p, sampleLayers: sample, resolved, steps: 32, strengths: [0, 0, 0, 0] }), 1)
      );
      t.ok(
        'a sun overhead casts nothing (the noon no-op)',
        layerSmearVisibility({
          ...p,
          sampleLayers: sample,
          resolved: resolveLayerSmear({ azimuthDeg: 220, elevationDeg: 90, heightsPx: [400, 0, 0, 0] }),
          steps: 32,
        }) === 1
      );
      t.ok(
        'an empty stack casts nothing',
        layerSmearVisibility({
          ...p,
          sampleLayers: () => [0, 0, 0, 0],
          resolved,
          steps: 32,
        }) === 1
      );
      const allFinite = [0, 45, 90, 135, 180, 225, 270, 315].every((az) =>
        [3, 15, 30, 60, 89].every((el) => {
          const v = layerSmearVisibility({
            x: CX + 500,
            y: CY + 300,
            sampleLayers: rects([box(300), box(500), box(700), box(900)]),
            resolved: resolveLayerSmear({ azimuthDeg: az, elevationDeg: el, heightsPx: [300, 500, 900, 1400] }),
            steps: 24,
          });
          return Number.isFinite(v) && v >= 0 && v <= 1;
        })
      );
      t.ok('every reading stays in [0,1] across a full sweep of the sky', allFinite);
    }

    t.ok('the layer count is the one RGBA texture the plan budgets for', SHADOW_LAYER_COUNT === 4);

    // ══════════════════════════════════════════════════════════════════
    // 🌉 THE SKY-REACH GRADIENT (2026-08-02) — author, live, on the FIRST
    // real-map render: "a soft gradient for the sky reach so that it gets
    // darker as it gets further in which should make the most middle
    // section of the bridge even darker but still a little bit of light
    // should leak through."
    // ══════════════════════════════════════════════════════════════════
    {
      const CX2 = 4000,
        CY2 = 4000;
      // A WIDE slab standing in for a bridge deck — much wider than the
      // depth radius under test, so its centre is genuinely "further in"
      // than the radius can reach from either edge.
      const wideHalf = 900;
      const depthRadius = 220;
      const wideSlab = (x, y) => {
        const inside = x >= CX2 - wideHalf && x <= CX2 + wideHalf && y >= CY2 - wideHalf && y <= CY2 + wideHalf;
        return {
          skyReachCoverage: 0,
          floatingHeightPx: 0,
          floatingCoverage: 0,
          buildingCoverage: 0,
          layers: [0, 0, inside ? 1 : 0, 0],
        };
      };
      // `layerSmearVisibility` reads layer index directly from the array
      // `sampleLayers` returns — build that shape explicitly here rather
      // than reusing `rects()` (which targets the older 4-box helper).
      const sampleWide = (x, y) => wideSlab(x, y).layers;
      const heights = [0, 0, 500, 0];
      const resolvedWide = resolveLayerSmear({ azimuthDeg: 220, elevationDeg: 30, heightsPx: heights });
      const common2 = { sampleLayers: sampleWide, resolved: resolvedWide, steps: 32, strengths: [1, 1, 0.75, 1] };

      // ── REGRESSION: depthRadiusPx defaults to 0 — untouched by default ──
      {
        const withoutArg = layerSmearVisibility({ ...common2, x: CX2, y: CY2 });
        const withZero = layerSmearVisibility({ ...common2, x: CX2, y: CY2, depthRadiusPx: [0, 0, 0, 0] });
        t.ok(
          'omitting depthRadiusPx and passing all-zero are identical (the default changes nothing)',
          near(withoutArg, withZero)
        );
      }

      // ── IT DEEPENS GRADUALLY ACROSS THE WHOLE RADIUS ──────────────────
      // Author, on the single-radius version: "This is the furthest from the
      // bridge edge and I'd like the middle of this sky reach bit to be
      // darkest and darker."
      //
      // ⚠️ THE RADIUS IS THE "FULLY ENCLOSED" DISTANCE, BY DESIGN. Any
      // isotropic read saturates once every one of its samples lands on solid
      // — for a multi-scale read, that is at its WIDEST radius. So the honest
      // claim is not "descends forever" (an earlier draft of this test
      // asserted that and failed, correctly): it is that the descent is
      // GRADUAL across [0, r] rather than a single step at one distance,
      // which is exactly what one radius could not deliver and three can.
      //
      // The tuning consequence is real and worth stating: to make the MIDDLE
      // of a span the darkest point, `r` must be about HALF that span's
      // width. A radius much smaller than the span leaves a flat saturated
      // plateau through the centre — which is the same flatness the author
      // asked to remove, just relocated.
      {
        const readAtDepth = (depthIntoSlab) =>
          layerSmearVisibility({
            ...common2,
            x: CX2 - wideHalf + depthIntoSlab,
            y: CY2,
            depthRadiusPx: [0, 0, depthRadius, 0],
          });
        const steps = [0.15, 0.35, 0.6, 0.85].map((f) => readAtDepth(Math.round(depthRadius * f)));
        let strictlyDescending = true;
        for (let i = 1; i < steps.length; i++) {
          if (steps[i] >= steps[i - 1] - 1e-6) strictlyDescending = false;
        }
        t.ok(
          `the gradient descends at EVERY step across its radius, not in one jump ` +
            `(${steps.map((v) => v.toFixed(3)).join(' → ')})`,
          strictlyDescending
        );
        // And it does saturate at the radius — asserted rather than left
        // implicit, because it is the fact that decides how `r` must be tuned.
        const atR = readAtDepth(depthRadius);
        const wellPastR = readAtDepth(Math.round(depthRadius * 2.5));
        t.ok(
          `it reaches full depth AT the radius and holds there — so r is the "fully enclosed" dial ` +
            `(1r=${atR.toFixed(3)}, 2.5r=${wellPastR.toFixed(3)})`,
          near(atR, wellPastR, 1e-6)
        );
      }

      // ── THE ACTUAL CLAIM: centre is darker than near an edge ─────────
      {
        const centre = layerSmearVisibility({ ...common2, x: CX2, y: CY2, depthRadiusPx: [0, 0, depthRadius, 0] });
        const nearEdge = layerSmearVisibility({
          ...common2,
          x: CX2 - wideHalf + 15,
          y: CY2,
          depthRadiusPx: [0, 0, depthRadius, 0],
        });
        t.ok(
          `the centre of a wide slab is darker than a point just inside its edge (centre=${centre.toFixed(3)}, nearEdge=${nearEdge.toFixed(3)})`,
          centre < nearEdge - 1e-6
        );
        // Without the gradient, the OLD behaviour: both points read IDENTICAL
        // (the march's own d=0 station already saturates the whole interior),
        // which is precisely the flatness the author asked to fix.
        const centreFlat = layerSmearVisibility({ ...common2, x: CX2, y: CY2, depthRadiusPx: [0, 0, 0, 0] });
        const nearEdgeFlat = layerSmearVisibility({
          ...common2,
          x: CX2 - wideHalf + 15,
          y: CY2,
          depthRadiusPx: [0, 0, 0, 0],
        });
        t.ok(
          'confirms the OLD flatness this feature fixes: without it, centre and near-edge read the same',
          near(centreFlat, nearEdgeFlat, 1e-6)
        );
      }

      // ── LIGHT STILL LEAKS THROUGH, EVEN AT THE DEEPEST POINT ─────────
      {
        const centreDeep = layerSmearVisibility({
          ...common2,
          x: CX2,
          y: CY2,
          depthRadiusPx: [0, 0, depthRadius, 0],
          strengths: [1, 1, 0.6, 1],
        });
        t.ok(
          `strength < 1 guarantees SOME light even at the most enclosed point (centre vis=${centreDeep.toFixed(3)})`,
          centreDeep > 0.35 && centreDeep < 1
        );
      }

      // ── HEIGHT GATING: a height-0 layer gets no depth term regardless ──
      {
        const offHeights = [0, 0, 0, 0]; // "above" height 0 — layer is OFF
        const resolvedOff = resolveLayerSmear({ azimuthDeg: 220, elevationDeg: 30, heightsPx: offHeights });
        const v = layerSmearVisibility({
          x: CX2,
          y: CY2,
          sampleLayers: sampleWide,
          resolved: resolvedOff,
          steps: 32,
          depthRadiusPx: [0, 0, depthRadius, 0],
        });
        t.ok('a height-0 layer stays fully lit even with a depth radius set — height is the OFF switch', near(v, 1));
      }

      // ── THE LAW STILL HOLDS OUTWARD, WITH THE GRADIENT ENABLED ────────
      // The architectural claim (this module's own header): the gradient
      // answers a DIFFERENT question (how deep in) from THE LAW (how far
      // OUTWARD from the caster), and for a receiver walking away from the
      // slab's edge into open ground, both the march term and the isotropic
      // term independently decrease — checked here, not just reasoned.
      {
        const toSun = marchDirectionToSun(220);
        const shadowDir = { x: -toSun.x, y: -toSun.y };
        const edgeX = CX2 + wideHalf,
          edgeY = CY2;
        let worst = 0;
        let prev = null;
        for (let d = 0; d <= 900; d += 15) {
          const v = layerSmearVisibility({
            x: edgeX + shadowDir.x * d,
            y: edgeY + shadowDir.y * d,
            sampleLayers: sampleWide,
            resolved: resolvedWide,
            steps: 32,
            strengths: [1, 1, 0.75, 1],
            depthRadiusPx: [0, 0, depthRadius, 0],
          });
          if (prev !== null) worst = Math.max(worst, prev - v);
          prev = v;
        }
        t.ok(`THE LAW still holds outward with the gradient enabled (worst rise ${worst.toFixed(4)})`, worst < 0.02);
      }
    }
  }

  // ══════════════════════════════════════════════════════════════════
  // 🪵 A LAYER NEVER SHADOWS ITS OWN FOOTPRINT (author, live 2026-08-02:
  // *"a shadow which is created by a tile with elevation is being composited
  // on top of the thing that is creating it. It should be underneath."*)
  //
  // Foundry elevation is a SORT KEY, not a spatial offset — a raised tile's
  // sprite sits at the very same (x,y) as the ground it is "above" — so
  // station 0 handed an overhead tile its own coverage as a full-strength
  // shadow and it darkened itself.
  //
  // The ASYMMETRY is the load-bearing part, and both halves are pinned: the
  // overhead layer self-excludes, the floor-above layer must NOT (excluding
  // it would delete the bridge-deck-over-water shadow, which is the one
  // picture this whole model exists to draw).
  // ══════════════════════════════════════════════════════════════════
  {
    const HALF = 300;
    // One square slab, present in whichever layer the caller names.
    const slabInLayer = (layerIndex) => (sx, sy) => {
      const out = new Array(SHADOW_LAYER_COUNT).fill(0);
      if (Math.abs(sx) <= HALF && Math.abs(sy) <= HALF) out[layerIndex] = 1;
      return out;
    };
    // Layer heights: only the layer under test throws anything.
    const heightsFor = (layerIndex) => {
      const h = [0, 0, 0, 0];
      h[layerIndex] = 400;
      return h;
    };
    const visAt = (layerIndex, x, y) =>
      layerSmearVisibility({
        x,
        y,
        sampleLayers: slabInLayer(layerIndex),
        resolved: resolveLayerSmear({ azimuthDeg: 220, elevationDeg: 30, heightsPx: heightsFor(layerIndex) }),
        steps: 32,
      });

    // ON the slab itself.
    const onOverhead = visAt(1, 0, 0);
    const onAbove = visAt(2, 0, 0);
    t.ok(
      `🔒 a receiver standing ON an overhead tile is NOT shadowed by that tile (got ${onOverhead.toFixed(3)})`,
      onOverhead > 0.99
    );
    t.ok(
      `the floor-ABOVE layer still darkens the ground beneath it — the asymmetry, not a blanket rule ` +
        `(got ${onAbove.toFixed(3)})`,
      onAbove < 0.2
    );

    // The overhead tile must still cast onto the ground BESIDE it — the fix
    // must not switch the layer off, only stop it darkening itself.
    // ⚠️ `HALF * Math.SQRT2`, NOT `HALF` — a square's DIAGONAL half-extent is
    // wider than its edge-on one, and azimuth 220° is not axis-aligned, so
    // `HALF + 60` is still INSIDE the slab. Caught by the non-vacuity
    // assertion below reading exactly 1.000 (this suite's retired smear block
    // documented the identical trap; it is easy to walk into twice).
    const toSun = marchDirectionToSun(220);
    const outside = HALF * Math.SQRT2 + 60;
    const beside = { x: -toSun.x * outside, y: -toSun.y * outside };
    const besideVis = visAt(1, beside.x, beside.y);
    t.ok(`an overhead tile still casts onto the open ground beside it (got ${besideVis.toFixed(3)})`, besideVis < 0.9);

    // NON-VACUITY: without the exclusion the on-tile reading would be dark.
    // Its own cast shadow just outside proves the layer is genuinely active,
    // so "1.0 on the tile" cannot be passing merely because nothing casts.
    t.ok('the overhead self-exclusion test is not vacuous — that same layer demonstrably casts', besideVis < 0.9);

    // ── WALLS gets the identical exclusion, added a session later ────────
    // (2026-08-03 — see layer-smear.js's own comment, in this same self-
    // shadow block, for the field bug this closes: `gate` alone only
    // protects a receiver that reads UNAMBIGUOUSLY indoors). Mirrors the
    // overhead assertions above exactly, on a fully-covered texel.
    const onWalls = visAt(LAYER_WALLS, 0, 0);
    t.ok(
      `🔒 a receiver on a FULLY wall-covered texel is not shadowed by that same wall (got ${onWalls.toFixed(3)})`,
      onWalls > 0.99
    );
    const wallsBesideVis = visAt(LAYER_WALLS, beside.x, beside.y);
    t.ok(`a wall still casts onto the open ground beside it (got ${wallsBesideVis.toFixed(3)})`, wallsBesideVis < 0.9);
  }

  // ══════════════════════════════════════════════════════════════════
  // 🏚️ PARTIAL SELF-COVERAGE — THE ACTUAL FIELD BUG (2026-08-03)
  //
  // Author, live, on a thatched roof: a dark band sat directly on the
  // ridge line, self-cast. Measured with the mask-stack probe: the ridge is
  // an ANTIALIASED edge in the roof's own `_Outdoors` art — walls-coverage
  // ≈0.51 there, not the clean 0/1 the block above exercises. The block
  // above proves the exclusion kills a FULLY-covered self-read; this proves
  // it also DISCOUNTS a PARTIALLY-covered one proportionally, rather than
  // leaving it at full undischarged strength because it never reaches 1.0
  // (which is exactly how this bug shipped: `gate` reads "outdoors enough"
  // for a 0.51-covered texel and lets the shadow through in full, and
  // nothing else was ever discounting the walls layer's own contribution).
  // ══════════════════════════════════════════════════════════════════
  {
    const HALF = 300;
    const partialCoverage = 0.51;
    const partialWallSlab = (sx, sy) => {
      const out = new Array(SHADOW_LAYER_COUNT).fill(0);
      if (Math.abs(sx) <= HALF && Math.abs(sy) <= HALF) out[LAYER_WALLS] = partialCoverage;
      return out;
    };
    const heights = [0, 0, 0, 0];
    heights[LAYER_WALLS] = 400;
    const resolved = resolveLayerSmear({ azimuthDeg: 220, elevationDeg: 30, heightsPx: heights });
    const onPartialWall = layerSmearVisibility({ x: 0, y: 0, sampleLayers: partialWallSlab, resolved, steps: 32 });

    // Station 0 (d=0, fall=1) reads this SAME partial coverage as the
    // march's own worst (largest) term — inside a uniform box nothing later
    // can exceed it, since `fall` only decreases with distance — so the
    // discount is exactly `coverage · (1 − coverage)`, hand-derivable and
    // asserted precisely (verified against the live module: 0.7501, exact)
    // rather than with a loose bound that a partial fix could sneak past.
    const expectedVis = 1 - partialCoverage * (1 - partialCoverage);
    t.ok(
      `a PARTIALLY (${Math.round(partialCoverage * 100)}%) wall-covered receiver has its self-shadow discounted ` +
        `proportionally, not left at full strength (got ${onPartialWall.toFixed(4)}, expected ${expectedVis.toFixed(4)}) ` +
        `— the exact roof-ridge field bug`,
      near(onPartialWall, expectedVis, 1e-3)
    );
    // Without this fix the pre-existing code left this texel completely
    // undischarged: exactly `1 - partialCoverage = 0.49`. Pinning that
    // number too means a future edit that reintroduces the gap (e.g. an
    // `if (coverage >= 1)` short-circuit added "for performance") fails
    // LOUDLY against a known-wrong value, not just a vague inequality.
    t.ok(
      'the un-fixed reading (0.49) is NOT what this receiver gets — regression pin',
      !near(onPartialWall, 1 - partialCoverage, 1e-3)
    );

    // NON-VACUITY, mirrored: the same partially-covered wall still casts a
    // real shadow onto open ground beside it — proportionally weaker than
    // the fully-covered case (0.215, computed above) but still substantial,
    // confirming the fix discounts SELF-shadow only, never the wall's
    // output onto anything else.
    const toSun = marchDirectionToSun(220);
    const outside = HALF * Math.SQRT2 + 60;
    const beside = { x: -toSun.x * outside, y: -toSun.y * outside };
    const partialBesideVis = layerSmearVisibility({
      x: beside.x,
      y: beside.y,
      sampleLayers: partialWallSlab,
      resolved,
      steps: 32,
    });
    t.ok(
      `the same partially-covered wall still casts a real shadow beside it (got ${partialBesideVis.toFixed(3)})`,
      partialBesideVis < 0.9
    );
  }

  // ══════════════════════════════════════════════════════════════════════
  // THE SHADOW CASCADE (2026-08-05) — bands union, they do not compound
  // ══════════════════════════════════════════════════════════════════════
  //
  // Author: *"buildings which are several stories tall … have a much longer
  // larger shadow produced as a result of having access to the information for
  // all floors."* The band decomposition delivers LENGTH; these cases guard the
  // thing that makes extra length safe to add — that stacking more storeys must
  // not also stack more DARKNESS. `shadow-bands.js` proves the heights; this
  // proves the combiner that consumes them.
  {
    // A silhouette present in BOTH bands (the nested case — `coverAbove(F+1) ⊆
    // coverAbove(F)` by construction, so a tall building is in every band).
    const inBothBands = () => {
      const a = new Array(SHADOW_LAYER_COUNT).fill(0);
      for (const i of SHADOW_BAND_LAYER_INDICES) a[i] = 1;
      return a;
    };
    const inNearBandOnly = () => {
      const a = new Array(SHADOW_LAYER_COUNT).fill(0);
      a[SHADOW_BAND_LAYER_INDICES[0]] = 1;
      return a;
    };
    const heights = new Array(SHADOW_LAYER_COUNT).fill(0);
    heights[SHADOW_BAND_LAYER_INDICES[0]] = 400;
    heights[SHADOW_BAND_LAYER_INDICES[1]] = 1060;
    const resolved = resolveLayerSmear({ azimuthDeg: 220, elevationDeg: 45, heightsPx: heights });
    const strengths = new Array(SHADOW_LAYER_COUNT).fill(0.95);

    const both = layerSmearVisibility({ x: 0, y: 0, sampleLayers: inBothBands, resolved, strengths, steps: 32 });
    const one = layerSmearVisibility({ x: 0, y: 0, sampleLayers: inNearBandOnly, resolved, strengths, steps: 32 });
    // ⚠️ THE HEADLINE INVARIANT. If the bands multiplied (the combiner every
    // OTHER layer in this model uses), `both` would be 0.05² = 0.0025 against
    // `one`'s 0.05 — a three-storey building reading twenty times blacker than
    // a two-storey one for no physical reason, and getting blacker still with
    // every floor added. `max` makes an occluder present at two elevations
    // exactly as opaque as one present at one.
    t.ok(
      `a building in BOTH bands is no darker than one in a single band (${both.toFixed(4)} vs ${one.toFixed(4)})`,
      near(both, one, 1e-9)
    );
    t.ok(
      `and both leave the author's "a little light should leak through" headroom (${both.toFixed(4)} > 0)`,
      both > 0 && both < 0.2
    );

    // The bands are ONE occluder; walls and overhead are DIFFERENT occluders in
    // series and must still compound. Proving one without the other would let a
    // change that turned the whole model into a `max` pass go unnoticed.
    //
    // ⚠️ THE WALL MUST BE LOCAL AND THE RECEIVER MUST STAND OUTSIDE IT. A first
    // version of this case put the wall EVERYWHERE (like the bands) and read
    // exactly the band-only value — because the receiver then stands inside the
    // wall's own silhouette, where the self-exclusion rule correctly discounts
    // the whole wall term to zero. The test looked like a compounding failure
    // and was a geometry mistake; `feedback_real_geometry_sweep_needs_occluder_
    // stop` is the same trap on a bigger sweep.
    const WALL_RADIUS = 40;
    const bandsEverywhereWallHere = (x, y) => {
      const a = inBothBands();
      if (Math.hypot(x, y) <= WALL_RADIUS) a[LAYER_WALLS] = 1;
      return a;
    };
    const wallHeights = [...heights];
    wallHeights[LAYER_WALLS] = 260;
    const seriesResolved = resolveLayerSmear({ azimuthDeg: 220, elevationDeg: 45, heightsPx: wallHeights });
    const toSunSeries = marchDirectionToSun(220);
    const outside = WALL_RADIUS + 20;
    const at = { x: -toSunSeries.x * outside, y: -toSunSeries.y * outside };
    const bandAndWall = layerSmearVisibility({
      ...at,
      sampleLayers: bandsEverywhereWallHere,
      resolved: seriesResolved,
      strengths,
      steps: 32,
    });
    const bandOnlySeries = layerSmearVisibility({
      ...at,
      sampleLayers: inBothBands,
      resolved: seriesResolved,
      strengths,
      steps: 32,
    });
    t.ok(
      `a wall AND a stack above still compound — different occluders in series ` +
        `(${bandAndWall.toFixed(4)} < ${bandOnlySeries.toFixed(4)})`,
      bandAndWall < bandOnlySeries
    );

    // A layer with strength 0 must contribute nothing, INCLUDING through the
    // band `max` — the debug isolation views work by zeroing strengths, and a
    // `max` taken before the strength multiply would ignore them entirely
    // (which is exactly how this effect's isolation views broke once before).
    const farOnlyStrengths = new Array(SHADOW_LAYER_COUNT).fill(0);
    farOnlyStrengths[SHADOW_BAND_LAYER_INDICES[1]] = 0.95;
    const farIsolated = layerSmearVisibility({
      x: 0,
      y: 0,
      sampleLayers: inNearBandOnly,
      resolved,
      strengths: farOnlyStrengths,
      steps: 32,
    });
    t.ok(
      `isolating the FAR band hides a caster that only exists in the near one (got ${farIsolated.toFixed(4)})`,
      near(farIsolated, 1, 1e-9)
    );
  }

  // ── THE DIFFUSION FLOOR — "softer and more diffuse as they cascade down" ──
  {
    t.ok('a zero-height layer diffuses nothing', layerDiffusionBlurPx(0) === 0);
    t.ok(
      'diffusion is linear in the caster height — twice as far up, twice as soft',
      near(layerDiffusionBlurPx(800), layerDiffusionBlurPx(400) * 2)
    );
    t.ok(
      `it is the shared atmospheric softness that scales it, so night-under-cloud stays the softest case`,
      near(layerDiffusionBlurPx(400, 2), layerDiffusionBlurPx(400) * 2)
    );
    // ⚠️ THE REASON THIS TERM EXISTS AT ALL, asserted rather than described: at
    // a HIGH sun the directional throw collapses toward zero, so the station
    // blur (which scales with throw) reports a roof three storeys up as exactly
    // as crisp as a kerbstone. The height term does not.
    const noonWall = resolveLayerSmear({ azimuthDeg: 220, elevationDeg: 85, heightsPx: [260, 0, 0, 0] });
    const noonRoof = resolveLayerSmear({ azimuthDeg: 220, elevationDeg: 85, heightsPx: [1060, 0, 0, 0] });
    t.ok(
      `at a near-overhead sun both throws are short (${noonWall.maxThrowPx.toFixed(0)}px, ` +
        `${noonRoof.maxThrowPx.toFixed(0)}px) …`,
      noonWall.maxThrowPx < 200 && noonRoof.maxThrowPx < 400
    );
    t.ok(
      '… yet the taller caster is still markedly softer, which is the whole point of the term',
      layerDiffusionBlurPx(noonRoof.heightPx[0]) > layerDiffusionBlurPx(noonWall.heightPx[0]) * 3
    );
    t.ok(
      "the constant stays above the sun's own ~0.0093 physical value (it is a LOOK constant, stated not implied)",
      DIFFUSION_PER_HEIGHT_PX > 0.0093
    );
    // Garbage in must not become a NaN mip request in the shader.
    t.ok(
      'non-finite inputs return a finite 0 rather than a NaN blur radius',
      layerDiffusionBlurPx(Number.NaN) === 0 &&
        layerDiffusionBlurPx(-5) === 0 &&
        Number.isFinite(layerDiffusionBlurPx(400, Number.NaN))
    );
  }

  // ── `resolveLayerSmear` CARRIES THE HEIGHTS THROUGH ──────────────────
  // The shader needs the HEIGHT as well as the throw, and cannot recover one
  // from the other: the dawn/dusk cap can land two very different heights on
  // the same capped throw, and inverting a cap on the GPU would be re-deriving
  // a CPU decision from its own lossy output.
  {
    const r = resolveLayerSmear({ azimuthDeg: 90, elevationDeg: 10, heightsPx: [260, 0, 400, 1060] });
    t.ok('every layer gets a height entry', r.heightPx.length === SHADOW_LAYER_COUNT);
    t.ok('the heights come through unchanged', r.heightPx[LAYER_WALLS] === 260 && r.heightPx[3] === 1060);
    t.ok('an absent layer resolves to height 0, not undefined', r.heightPx[LAYER_OVERHEAD] === 0);
    // The cap really does collapse two heights onto one throw at a low sun —
    // which is the case that makes the second array necessary rather than
    // merely convenient.
    const capped = resolveLayerSmear({
      azimuthDeg: 90,
      elevationDeg: 1,
      heightsPx: [400, 1060, 0, 0],
      maxLengthMul: 2,
    });
    t.ok(
      `a low sun caps both throws proportionally while the heights stay distinct ` +
        `(${capped.throwPx[0]}/${capped.throwPx[1]} px from ${capped.heightPx[0]}/${capped.heightPx[1]})`,
      capped.heightPx[0] !== capped.heightPx[1] && capped.throwPx[0] === 800 && capped.throwPx[1] === 2120
    );
    t.ok(
      'a non-finite height is sanitised to 0 by the resolve, so the shader never sees it',
      resolveLayerSmear({ azimuthDeg: 0, elevationDeg: 45, heightsPx: [Number.NaN, -3] }).heightPx.every((h) => h === 0)
    );
  }
}
