/**
 * THE LAYER SMEAR MODEL — asserted, not admired.
 * Plan of record: `docs/planning/Sun-Shadows-Layer-Smear.md`.
 *
 * The load-bearing test in this file is THE LAW: *"We cannot have a shadow which
 * is generated by opaque occluders which ever goes from black to grey to white
 * to grey to white"* (author, 2026-08-02). Two previous shadow models each
 * shipped a violation of it that looked plausible on screen — a bright halo
 * hugging every building, and a detached second shadow further out — so it is
 * pinned here across many silhouettes, sun angles and step counts rather than
 * argued for in a comment.
 *
 * The model's monotonicity PROOF (see `layer-smear.js`'s header) consumes
 * exactly one property: that the falloff decreases. That single precondition
 * gets its own test first, because if it ever stops holding, every other
 * guarantee in this file evaporates silently.
 */
import {
  SHADOW_LAYER_COUNT,
  layerThrowPx,
  smearFalloff01,
  stationDistancePx,
  stationSpacingPx,
  resolveLayerSmear,
  layerSmearVisibility,
} from '../layer-smear.js';
import { marchDirectionToSun } from '../sun-occlusion.js';

const near = (a, b, eps = 1e-6) => Math.abs(a - b) < eps;

/** @param {{ok:(name:string, cond:boolean)=>void}} t */
export function run(t) {
  // ── THE FALLOFF — THE LAW'S ONE PRECONDITION ─────────────────────────
  {
    let strictlyDecreasing = true;
    for (const e of [0.5, 1, 1.6, 2.5, 4]) {
      let prev = Infinity;
      for (let i = 0; i <= 200; i++) {
        const v = smearFalloff01(i / 200, e);
        if (v > prev + 1e-12) strictlyDecreasing = false;
        prev = v;
      }
    }
    t.ok('the falloff decreases monotonically on [0,1] for every exponent — THE LAW rests on this', strictlyDecreasing);
    t.ok('fully dark against its caster', near(smearFalloff01(0, 1.6), 1));
    t.ok('exactly gone at the throw distance — no hard tip', near(smearFalloff01(1, 1.6), 0));
    t.ok('past the throw distance stays gone', smearFalloff01(1.5, 1.6) === 0 && smearFalloff01(9, 1.6) === 0);
  }

  // ── THROW LENGTH ─────────────────────────────────────────────────────
  {
    t.ok('a 100px layer at 45° throws 100px', near(layerThrowPx({ heightPx: 100, elevationDeg: 45 }), 100, 1e-9));
    t.ok(
      'the same layer reaches further as the sun lowers',
      layerThrowPx({ heightPx: 100, elevationDeg: 20 }) > layerThrowPx({ heightPx: 100, elevationDeg: 60 })
    );
    t.ok('a sun overhead throws nothing', near(layerThrowPx({ heightPx: 100, elevationDeg: 90 }), 0, 1e-6));
    t.ok('a zero-height layer throws nothing', layerThrowPx({ heightPx: 0, elevationDeg: 10 }) === 0);
    const grazing = layerThrowPx({ heightPx: 100, elevationDeg: 0 });
    t.ok(
      'a sun ON the horizon saturates at a cap — never Infinity, never NaN',
      Number.isFinite(grazing) && grazing > 0
    );
    t.ok(
      'lengthScale shortens every shadow',
      layerThrowPx({ heightPx: 200, elevationDeg: 30, lengthScale: 0.5 }) <
        layerThrowPx({ heightPx: 200, elevationDeg: 30 })
    );
    t.ok(
      'maxLengthMul caps the dawn blow-up but leaves midday alone',
      layerThrowPx({ heightPx: 100, elevationDeg: 5, maxLengthMul: 3 }) <= 300 + 1e-6 &&
        near(layerThrowPx({ heightPx: 100, elevationDeg: 45, maxLengthMul: 3 }), 100, 1e-6)
    );
  }

  // ── STATION LADDER ───────────────────────────────────────────────────
  {
    const n = 32;
    const L = 640;
    t.ok('station 0 is the receiver itself', stationDistancePx(0, n, L) === 0);
    t.ok('the last station lands exactly on the throw distance', near(stationDistancePx(n, n, L), L, 1e-9));
    let increasing = true;
    for (let j = 1; j <= n; j++) {
      if (stationDistancePx(j, n, L) <= stationDistancePx(j - 1, n, L)) increasing = false;
    }
    t.ok('stations advance strictly outward', increasing);
    t.ok(
      'stations bunch toward the caster — the first gap is far smaller than the last',
      stationDistancePx(1, n, L) - stationDistancePx(0, n, L) <
        (stationDistancePx(n, n, L) - stationDistancePx(n - 1, n, L)) / 10
    );
    // The spacing helper is the shader's anti-aliasing floor; if it under-reports
    // the true gap, a thin caster can hide between two stations and THE LAW
    // breaks discretely (memory: feedback_narrow_tolerance_between_march_samples).
    let coversEveryGap = true;
    for (let j = 1; j <= n; j++) {
      const trueGap = stationDistancePx(j, n, L) - stationDistancePx(j - 1, n, L);
      if (stationSpacingPx(j, n, L) < trueGap - 1e-9) coversEveryGap = false;
    }
    t.ok('the reported station spacing is never NARROWER than the real gap it must cover', coversEveryGap);
  }

  // ══════════════════════════════════════════════════════════════════════
  // ⚖️ THE LAW — a shadow may only ever get lighter with distance
  // ══════════════════════════════════════════════════════════════════════
  {
    /** Build a `sampleLayers` over a set of axis-aligned rectangles, one per
     * layer. Clamp-to-edge is irrelevant here (nothing runs off), so this is a
     * plain point test. */
    const rects = (specs) => (x, y) =>
      specs.map((r) => (r && x >= r.x0 && x <= r.x1 && y >= r.y0 && y <= r.y1 ? 1 : 0));

    const CX = 2000;
    const CY = 2000;
    const box = (half) => ({ x0: CX - half, x1: CX + half, y0: CY - half, y1: CY + half });

    /** Walk outward from the caster along the direction a shadow is THROWN and
     * return the visibility profile. */
    const profile = (sampleLayers, heightsPx, azimuthDeg, elevationDeg, steps, startPx, endPx, n = 120) => {
      const toSun = marchDirectionToSun(azimuthDeg);
      const shadowDir = { x: -toSun.x, y: -toSun.y };
      const resolved = resolveLayerSmear({ azimuthDeg, elevationDeg, heightsPx });
      const out = [];
      for (let i = 0; i <= n; i++) {
        const d = startPx + ((endPx - startPx) * i) / n;
        out.push({
          d,
          v: layerSmearVisibility({
            x: CX + shadowDir.x * d,
            y: CY + shadowDir.y * d,
            sampleLayers,
            resolved,
            steps,
          }),
        });
      }
      return out;
    };

    /** The worst RISE in occlusion (= drop in visibility) anywhere in a profile.
     * A tiny tolerance absorbs float noise; anything above it is a real
     * black→grey→BLACK curve, which is what the author is looking at. */
    const worstDrop = (prof) => {
      let worst = 0;
      let at = null;
      for (let i = 1; i < prof.length; i++) {
        const drop = prof[i - 1].v - prof[i].v;
        if (drop > worst) {
          worst = drop;
          at = prof[i].d;
        }
      }
      return { worst, at };
    };

    // ── One wall, swept across the whole sky ────────────────────────────
    {
      const sample = rects([box(300), null, null, null]);
      let worstEver = 0;
      let worstCase = null;
      for (const az of [0, 37, 90, 143, 180, 220, 270, 315]) {
        for (const el of [8, 20, 35, 55, 75]) {
          for (const steps of [16, 32, 64]) {
            const p = profile(sample, [400, 0, 0, 0], az, el, steps, 305, 2200);
            const { worst, at } = worstDrop(p);
            if (worst > worstEver) {
              worstEver = worst;
              worstCase = { az, el, steps, at };
            }
          }
        }
      }
      t.ok(
        `a single wall NEVER darkens with distance, across 8 azimuths x 5 elevations x 3 step counts ` +
          `(worst rise ${worstEver.toFixed(4)}${worstCase ? ` at ${JSON.stringify(worstCase)}` : ''})`,
        worstEver < 0.02
      );
    }

    // ⚠️ THE SINGLE-WALL SWEEP ABOVE CANNOT CATCH A BAD FALLOFF, and knowing
    // that is what makes the next block load-bearing rather than decorative.
    // Sabotage-tested 2026-08-02 with a deliberately non-monotonic `f`: the
    // wall sweep still PASSED. For one convex occluder, `occ(x) = max over
    // d ≥ x of f(d/L)` — a max over an interval that only ever SHRINKS as the
    // receiver moves away, and a max over a shrinking interval is non-increasing
    // whatever shape `f` has. The `max` hides the defect. Only DISJOINT,
    // staggered occluders let the argmax jump between features and expose it,
    // which the four-layer sweep below does and which is also the exact shape
    // that produced the author's detached "second shadow".
    //
    // ── The full four-layer stack, which is where the previous model broke ──
    // A wall, an overhead slab offset one way, and two upper floors offset
    // another — deliberately staggered so their throws end at different
    // distances. That staggering is EXACTLY the shape that produced the
    // author's detached "second shadow" under a shared mean.
    {
      const sample = rects([
        box(300),
        { x0: CX - 700, x1: CX + 100, y0: CY - 200, y1: CY + 600 },
        { x0: CX - 200, x1: CX + 900, y0: CY - 900, y1: CY + 200 },
        { x0: CX - 1100, x1: CX + 400, y0: CY - 400, y1: CY + 1100 },
      ]);
      const heights = [300, 500, 900, 1400];
      let worstEver = 0;
      let worstCase = null;
      for (const az of [0, 45, 110, 180, 220, 300]) {
        for (const el of [10, 25, 45, 70]) {
          const p = profile(sample, heights, az, el, 48, 320, 4000, 200);
          const { worst, at } = worstDrop(p);
          if (worst > worstEver) {
            worstEver = worst;
            worstCase = { az, el, at };
          }
        }
      }
      t.ok(
        `a FOUR-LAYER stack with staggered throws never darkens with distance ` +
          `(worst rise ${worstEver.toFixed(4)}${worstCase ? ` at ${JSON.stringify(worstCase)}` : ''})`,
        worstEver < 0.02
      );
    }

    // ── Guard the guard: the sweeps above must actually see shadow ───────
    // A profile that is fully lit everywhere satisfies "never darkens"
    // vacuously, and would have passed on a model that cast nothing at all
    // (memory: feedback_instruments_must_not_lie).
    {
      const sample = rects([box(300), null, null, null]);
      const p = profile(sample, [400, 0, 0, 0], 220, 30, 32, 305, 2200);
      const darkest = Math.min(...p.map((r) => r.v));
      const lightest = Math.max(...p.map((r) => r.v));
      t.ok('THE LAW sweep is not vacuous: it passes through real shadow', darkest < 0.35);
      t.ok('THE LAW sweep is not vacuous: it also reaches real light', lightest > 0.9);
    }

    // ── DARKEST AGAINST THE CASTER — the author's stated requirement ─────
    {
      const sample = rects([box(300), null, null, null]);
      const p = profile(sample, [400, 0, 0, 0], 220, 30, 48, 302, 800, 60);
      t.ok('the shadow is at its darkest right against the wall', p[0].v === Math.min(...p.map((r) => r.v)));
    }

    // ── COMPOUNDING — a second occluder never lightens ───────────────────
    // The regression guard carried over from the previous model, where a shared
    // softmax mean measurably let a WEAK second shadow LIGHTEN a strong first
    // (memory: feedback_mean_cannot_compound_occluders).
    {
      const wall = box(300);
      const slab = { x0: CX - 700, x1: CX + 200, y0: CY - 300, y1: CY + 700 };
      const both = rects([wall, slab, null, null]);
      const wallOnly = rects([wall, null, null, null]);
      const slabOnly = rects([null, slab, null, null]);
      const heights = [300, 700, 0, 0];
      const toSun = marchDirectionToSun(220);
      const shadowDir = { x: -toSun.x, y: -toSun.y };
      const resolved = resolveLayerSmear({ azimuthDeg: 220, elevationDeg: 30, heightsPx: heights });
      const at = (sampleLayers, d) =>
        layerSmearVisibility({
          x: CX + shadowDir.x * d,
          y: CY + shadowDir.y * d,
          sampleLayers,
          resolved,
          steps: 48,
        });
      let everLighter = null;
      let sawBothActive = false;
      for (let d = 305; d <= 1600; d += 25) {
        const vb = at(both, d);
        const vw = at(wallOnly, d);
        const vs = at(slabOnly, d);
        if (vw < 0.98 && vs < 0.98) sawBothActive = true;
        if (vb > Math.min(vw, vs) + 1e-6)
          everLighter = { d, vb: +vb.toFixed(3), vw: +vw.toFixed(3), vs: +vs.toFixed(3) };
      }
      t.ok('compounding guard is not vacuous: some probe has BOTH layers casting', sawBothActive);
      t.ok('a second layer never lightens: both together is at least as dark as either alone', everLighter === null);
    }

    // ── THE EDGE RULE — a building running off the map keeps casting ─────
    // Author: *"If the black pixels of _Outdoors extend across the edge of the
    // map then we assume that this continues into the distance."* Modelled the
    // way the sampler models it: clamp the read to the rect.
    {
      const RECT = { minX: 0, minY: 0, maxX: 4000, maxY: 4000 };
      // A wall hard against the map's minX border, and NOTHING beyond it.
      const clamped = (x, y) => {
        const cx = Math.min(RECT.maxX, Math.max(RECT.minX, x));
        const cy = Math.min(RECT.maxY, Math.max(RECT.minY, y));
        return [cx <= 200 && cy >= 1500 && cy <= 2500 ? 1 : 0, 0, 0, 0];
      };
      // Sun in the −x direction (azimuth 270 walks the back-trace to −x), so a
      // receiver to the +x side of the border wall is in its shadow, and the
      // back-trace runs OFF the map.
      const resolved = resolveLayerSmear({ azimuthDeg: 270, elevationDeg: 30, heightsPx: [500, 0, 0, 0] });
      const onMap = layerSmearVisibility({ x: 260, y: 2000, sampleLayers: clamped, resolved, steps: 48 });
      t.ok('a wall on the map border still casts into the map', onMap < 0.6);
      // And the clamp must not invent a caster where the border is CLEAR.
      const clearBorder = () => [0, 0, 0, 0];
      const noCaster = layerSmearVisibility({ x: 260, y: 2000, sampleLayers: clearBorder, resolved, steps: 48 });
      t.ok('a clear border invents no shadow — clamping extends content, it does not create it', near(noCaster, 1));
    }

    // ── BOUNDS AND SWITCHES ──────────────────────────────────────────────
    {
      const sample = rects([box(300), null, null, null]);
      const resolved = resolveLayerSmear({ azimuthDeg: 220, elevationDeg: 30, heightsPx: [400, 0, 0, 0] });
      const toSun = marchDirectionToSun(220);
      const p = { x: CX - toSun.x * 400, y: CY - toSun.y * 400 };
      t.ok(
        'a closed receiver gate returns fully lit regardless of geometry',
        layerSmearVisibility({ ...p, sampleLayers: sample, resolved, steps: 32, receiverGate: 0 }) === 1
      );
      t.ok(
        'strength 0 returns exactly 1 however many layers are stacked',
        near(layerSmearVisibility({ ...p, sampleLayers: sample, resolved, steps: 32, strength: 0 }), 1)
      );
      t.ok(
        'a per-layer strength of 0 removes that layer entirely',
        near(layerSmearVisibility({ ...p, sampleLayers: sample, resolved, steps: 32, strengths: [0, 0, 0, 0] }), 1)
      );
      t.ok(
        'a sun overhead casts nothing (the noon no-op)',
        layerSmearVisibility({
          ...p,
          sampleLayers: sample,
          resolved: resolveLayerSmear({ azimuthDeg: 220, elevationDeg: 90, heightsPx: [400, 0, 0, 0] }),
          steps: 32,
        }) === 1
      );
      t.ok(
        'an empty stack casts nothing',
        layerSmearVisibility({
          ...p,
          sampleLayers: () => [0, 0, 0, 0],
          resolved,
          steps: 32,
        }) === 1
      );
      const allFinite = [0, 45, 90, 135, 180, 225, 270, 315].every((az) =>
        [3, 15, 30, 60, 89].every((el) => {
          const v = layerSmearVisibility({
            x: CX + 500,
            y: CY + 300,
            sampleLayers: rects([box(300), box(500), box(700), box(900)]),
            resolved: resolveLayerSmear({ azimuthDeg: az, elevationDeg: el, heightsPx: [300, 500, 900, 1400] }),
            steps: 24,
          });
          return Number.isFinite(v) && v >= 0 && v <= 1;
        })
      );
      t.ok('every reading stays in [0,1] across a full sweep of the sky', allFinite);
    }

    t.ok('the layer count is the one RGBA texture the plan budgets for', SHADOW_LAYER_COUNT === 4);

    // ══════════════════════════════════════════════════════════════════
    // 🌉 THE SKY-REACH GRADIENT (2026-08-02) — author, live, on the FIRST
    // real-map render: "a soft gradient for the sky reach so that it gets
    // darker as it gets further in which should make the most middle
    // section of the bridge even darker but still a little bit of light
    // should leak through."
    // ══════════════════════════════════════════════════════════════════
    {
      const CX2 = 4000,
        CY2 = 4000;
      // A WIDE slab standing in for a bridge deck — much wider than the
      // depth radius under test, so its centre is genuinely "further in"
      // than the radius can reach from either edge.
      const wideHalf = 900;
      const depthRadius = 220;
      const wideSlab = (x, y) => {
        const inside = x >= CX2 - wideHalf && x <= CX2 + wideHalf && y >= CY2 - wideHalf && y <= CY2 + wideHalf;
        return {
          skyReachCoverage: 0,
          floatingHeightPx: 0,
          floatingCoverage: 0,
          buildingCoverage: 0,
          layers: [0, 0, inside ? 1 : 0, 0],
        };
      };
      // `layerSmearVisibility` reads layer index directly from the array
      // `sampleLayers` returns — build that shape explicitly here rather
      // than reusing `rects()` (which targets the older 4-box helper).
      const sampleWide = (x, y) => wideSlab(x, y).layers;
      const heights = [0, 0, 500, 0];
      const resolvedWide = resolveLayerSmear({ azimuthDeg: 220, elevationDeg: 30, heightsPx: heights });
      const common2 = { sampleLayers: sampleWide, resolved: resolvedWide, steps: 32, strengths: [1, 1, 0.75, 1] };

      // ── REGRESSION: depthRadiusPx defaults to 0 — untouched by default ──
      {
        const withoutArg = layerSmearVisibility({ ...common2, x: CX2, y: CY2 });
        const withZero = layerSmearVisibility({ ...common2, x: CX2, y: CY2, depthRadiusPx: [0, 0, 0, 0] });
        t.ok(
          'omitting depthRadiusPx and passing all-zero are identical (the default changes nothing)',
          near(withoutArg, withZero)
        );
      }

      // ── IT DEEPENS GRADUALLY ACROSS THE WHOLE RADIUS ──────────────────
      // Author, on the single-radius version: "This is the furthest from the
      // bridge edge and I'd like the middle of this sky reach bit to be
      // darkest and darker."
      //
      // ⚠️ THE RADIUS IS THE "FULLY ENCLOSED" DISTANCE, BY DESIGN. Any
      // isotropic read saturates once every one of its samples lands on solid
      // — for a multi-scale read, that is at its WIDEST radius. So the honest
      // claim is not "descends forever" (an earlier draft of this test
      // asserted that and failed, correctly): it is that the descent is
      // GRADUAL across [0, r] rather than a single step at one distance,
      // which is exactly what one radius could not deliver and three can.
      //
      // The tuning consequence is real and worth stating: to make the MIDDLE
      // of a span the darkest point, `r` must be about HALF that span's
      // width. A radius much smaller than the span leaves a flat saturated
      // plateau through the centre — which is the same flatness the author
      // asked to remove, just relocated.
      {
        const readAtDepth = (depthIntoSlab) =>
          layerSmearVisibility({
            ...common2,
            x: CX2 - wideHalf + depthIntoSlab,
            y: CY2,
            depthRadiusPx: [0, 0, depthRadius, 0],
          });
        const steps = [0.15, 0.35, 0.6, 0.85].map((f) => readAtDepth(Math.round(depthRadius * f)));
        let strictlyDescending = true;
        for (let i = 1; i < steps.length; i++) {
          if (steps[i] >= steps[i - 1] - 1e-6) strictlyDescending = false;
        }
        t.ok(
          `the gradient descends at EVERY step across its radius, not in one jump ` +
            `(${steps.map((v) => v.toFixed(3)).join(' → ')})`,
          strictlyDescending
        );
        // And it does saturate at the radius — asserted rather than left
        // implicit, because it is the fact that decides how `r` must be tuned.
        const atR = readAtDepth(depthRadius);
        const wellPastR = readAtDepth(Math.round(depthRadius * 2.5));
        t.ok(
          `it reaches full depth AT the radius and holds there — so r is the "fully enclosed" dial ` +
            `(1r=${atR.toFixed(3)}, 2.5r=${wellPastR.toFixed(3)})`,
          near(atR, wellPastR, 1e-6)
        );
      }

      // ── THE ACTUAL CLAIM: centre is darker than near an edge ─────────
      {
        const centre = layerSmearVisibility({ ...common2, x: CX2, y: CY2, depthRadiusPx: [0, 0, depthRadius, 0] });
        const nearEdge = layerSmearVisibility({
          ...common2,
          x: CX2 - wideHalf + 15,
          y: CY2,
          depthRadiusPx: [0, 0, depthRadius, 0],
        });
        t.ok(
          `the centre of a wide slab is darker than a point just inside its edge (centre=${centre.toFixed(3)}, nearEdge=${nearEdge.toFixed(3)})`,
          centre < nearEdge - 1e-6
        );
        // Without the gradient, the OLD behaviour: both points read IDENTICAL
        // (the march's own d=0 station already saturates the whole interior),
        // which is precisely the flatness the author asked to fix.
        const centreFlat = layerSmearVisibility({ ...common2, x: CX2, y: CY2, depthRadiusPx: [0, 0, 0, 0] });
        const nearEdgeFlat = layerSmearVisibility({
          ...common2,
          x: CX2 - wideHalf + 15,
          y: CY2,
          depthRadiusPx: [0, 0, 0, 0],
        });
        t.ok(
          'confirms the OLD flatness this feature fixes: without it, centre and near-edge read the same',
          near(centreFlat, nearEdgeFlat, 1e-6)
        );
      }

      // ── LIGHT STILL LEAKS THROUGH, EVEN AT THE DEEPEST POINT ─────────
      {
        const centreDeep = layerSmearVisibility({
          ...common2,
          x: CX2,
          y: CY2,
          depthRadiusPx: [0, 0, depthRadius, 0],
          strengths: [1, 1, 0.6, 1],
        });
        t.ok(
          `strength < 1 guarantees SOME light even at the most enclosed point (centre vis=${centreDeep.toFixed(3)})`,
          centreDeep > 0.35 && centreDeep < 1
        );
      }

      // ── HEIGHT GATING: a height-0 layer gets no depth term regardless ──
      {
        const offHeights = [0, 0, 0, 0]; // "above" height 0 — layer is OFF
        const resolvedOff = resolveLayerSmear({ azimuthDeg: 220, elevationDeg: 30, heightsPx: offHeights });
        const v = layerSmearVisibility({
          x: CX2,
          y: CY2,
          sampleLayers: sampleWide,
          resolved: resolvedOff,
          steps: 32,
          depthRadiusPx: [0, 0, depthRadius, 0],
        });
        t.ok('a height-0 layer stays fully lit even with a depth radius set — height is the OFF switch', near(v, 1));
      }

      // ── THE LAW STILL HOLDS OUTWARD, WITH THE GRADIENT ENABLED ────────
      // The architectural claim (this module's own header): the gradient
      // answers a DIFFERENT question (how deep in) from THE LAW (how far
      // OUTWARD from the caster), and for a receiver walking away from the
      // slab's edge into open ground, both the march term and the isotropic
      // term independently decrease — checked here, not just reasoned.
      {
        const toSun = marchDirectionToSun(220);
        const shadowDir = { x: -toSun.x, y: -toSun.y };
        const edgeX = CX2 + wideHalf,
          edgeY = CY2;
        let worst = 0;
        let prev = null;
        for (let d = 0; d <= 900; d += 15) {
          const v = layerSmearVisibility({
            x: edgeX + shadowDir.x * d,
            y: edgeY + shadowDir.y * d,
            sampleLayers: sampleWide,
            resolved: resolvedWide,
            steps: 32,
            strengths: [1, 1, 0.75, 1],
            depthRadiusPx: [0, 0, depthRadius, 0],
          });
          if (prev !== null) worst = Math.max(worst, prev - v);
          prev = v;
        }
        t.ok(`THE LAW still holds outward with the gradient enabled (worst rise ${worst.toFixed(4)})`, worst < 0.02);
      }
    }
  }
}
