/**
 * THE LAYER SMEAR SHADOW MODEL — the maths, pure and Node-testable.
 * Plan of record: `docs/planning/Sun-Shadows-Layer-Smear.md`.
 *
 * ============================================================================
 * WHAT THIS IS
 * ============================================================================
 * A top-down map's shadow is a COMPOSITING problem, not a ray-marching one
 * (author, 2026-08-02, after two marching models failed): take a silhouette,
 * smear it in the sun's direction, fade it with distance, multiply the layers
 * together. That is the entire algorithm.
 *
 *     for each layer (silhouette S, height h, strength k):
 *         L    = h / tan(elevation)
 *         occ  = max over d in [0, L] of  S(p + toSun·d) · falloff(d / L)
 *         T   *= 1 − occ·k
 *     visibility = T
 *
 * `max` WITHIN a layer — those samples are one physical occluder seen from many
 * distances, a union, and compounding them is the p-norm bug that once
 * saturated a whole shadow to solid black. `×` BETWEEN layers — those are
 * different occluders in series, and light that clears the wall must still
 * clear the deck overhead (memory: feedback_mean_cannot_compound_occluders,
 * where a shared mean measurably let a WEAK second shadow LIGHTEN a strong
 * first one).
 *
 * ============================================================================
 * ⚖️ THE LAW, AND WHY IT CANNOT BE BROKEN HERE
 * ============================================================================
 * Author: *"We cannot have a shadow which is generated by opaque occluders
 * which ever goes from black to grey to white to grey to white. There should
 * never be a case where a shadow has that curve when dealing with one light
 * source and opaque occluders."*
 *
 * Move a receiver `p` further along the shadow direction by δ. Every back-trace
 * sample the new position reaches is one the old position also reached, but at
 * a GREATER distance:
 *
 *     occ(p + shadowDir·δ) = max_d [ S(p + toSun·(d − δ)) · f(d) ]
 *                          = max_d′ [ S(p + toSun·d′) · f(d′ + δ) ]
 *                          ≤ max_d′ [ S(p + toSun·d′) · f(d′) ]   ← f decreasing
 *                          = occ(p)
 *
 * Occlusion can only DECREASE with distance from the caster, for any silhouette
 * whatsoever. The proof consumes exactly one property — that `f` is monotonically
 * decreasing — which is why {@link smearFalloff01} is a named function with its
 * own test rather than an expression inlined at the call site. And since a
 * product of decreasing transmittances is itself decreasing, stacking layers
 * cannot break it either.
 *
 * ⚠️ THE PROOF IS CONTINUOUS; THE CODE IS DISCRETE. A finite set of stations can
 * still let a thin caster slip BETWEEN two samples, which would read as a rise.
 * The fix is not more stations — it is that every station samples a filtered
 * footprint at least as wide as the local station spacing, so nothing can hide
 * in the gap ({@link stationSpacingPx}, and §4's own anti-aliasing floor which
 * this model needs from birth rather than as a later repair). Both the CPU twin
 * and the shader honour it; the tests sweep for rises rather than trusting it.
 *
 * @module effects/lighting/layer-smear
 */
import { marchDirectionToSun } from './sun-occlusion.js';
import { SHADOW_BAND_LAYER_INDICES } from './shadow-bands.js';

/**
 * How many occluder layers the stack carries — ONE RGBA texture's worth, and a
 * deliberate hard bound rather than an open-ended list (the plan's §6):
 *
 *   0  this floor's WALLS    — `_Outdoors` dark, at the authored wall height
 *   1  this floor's OVERHEAD — overhead tiles hosted on this floor
 *   2  BAND 0 — `coverAbove(F)`,   every floor above, at the NEAREST one's real elevation
 *   3  BAND 1 — `coverAbove(F+1)`, every floor above THAT, at the stack's real top
 *
 * ⚠️ LAYERS 2 AND 3 CHANGED MEANING 2026-08-05 (the shadow cascade —
 * `shadow-bands.js`'s own header has the author's brief and the full
 * decomposition). They used to be "the floor directly above" and "everything
 * higher", both at ONE authored slider height, and layer 3 never carried a
 * silhouette at all (its channel was spent on the cascade's blend factor
 * instead, which now rides in the baked FIELD's own alpha). They are now two
 * cumulative bands at REAL, Foundry-derived elevations, which is what makes a
 * five-storey building throw a five-storey shadow instead of a one-storey one.
 */
export const SHADOW_LAYER_COUNT = 4;

/**
 * Named indices into that packing. Only the ones something actually branches
 * on are declared — a full set of four would be three unused constants, and
 * this file's own doctrine is that an unconsumed API rots silently.
 *
 * `LAYER_WALLS` and `LAYER_OVERHEAD` both exist because they are the layers
 * whose coverage can mean "the receiver IS this caster" rather than "the
 * receiver is beneath it", and {@link layerSmearVisibility} has to treat
 * both differently for exactly that reason. Naming them keeps that asymmetry
 * legible instead of a bare `occ[0]`/`occ[1]`.
 *
 * The two BAND layers are named by `shadow-bands.js` and re-exported here
 * rather than restated, so the packing, the model, the shader and the debug
 * view cannot end up with two ideas of which slot is which.
 */
export const LAYER_WALLS = 0;
export const LAYER_OVERHEAD = 1;
export { SHADOW_BAND_LAYER_INDICES };

/**
 * HOW MUCH A SHADOW DIFFUSES PER PIXEL OF FALL — the "softer as it cascades
 * downwards" term, in penumbra px per px of caster height.
 *
 * Author, 2026-08-05: *"allow shadows to semi-realistically cascade downwards,
 * getting softer and more diffuse as they do so."*
 *
 * ⚠️ THE EXISTING DISTANCE BLUR CANNOT DELIVER THIS, and the reason is worth
 * stating rather than re-discovering. The station blur
 * (`layer-smear-render.js`'s own `blurPx`) widens with distance ALONG THE
 * SHADOW — so at a low sun everything is soft and at a high sun everything is
 * crisp, regardless of how far the light actually fell. But a shadow's
 * penumbra is set by the caster's VERTICAL drop, not its horizontal throw: at
 * noon a roof three storeys up still casts a markedly softer edge than a
 * kerbstone, even though both throw almost nothing. Without a height term the
 * whole point of a multi-storey cascade — the tallest shadows reading as the
 * softest — is invisible at exactly the hours the shadows are most legible.
 *
 * The physical value is the sun's own angular diameter (~0.53°, i.e.
 * `tan ≈ 0.0093` px of penumbra per px of drop). This constant is
 * deliberately larger: it is a LOOK constant (this file's own doctrine —
 * `sun-shadow-subsystem.js`'s "LOOK CONSTANTS, NOT PARAMS" header), and it is
 * multiplied by the shared atmospheric `softnessMul`, whose own shipped
 * default (`softnessBias` 0.25) scales it back down to ≈0.03 — about three
 * times physical, which is what makes the effect readable at map zoom rather
 * than a sub-pixel technicality. Cloud and night soften it further through the
 * SAME multiplier every other caster in the scene already reads
 * (`effects/shadow-access.js`), so night-under-cloud remains the softest case
 * without a second model saying so.
 */
export const DIFFUSION_PER_HEIGHT_PX = 0.12;

/**
 * The minimum penumbra a layer's own height earns it, world px — the ONE
 * definition, shared by the CPU side (the bake's blur ledger, so a report can
 * say what the shader will actually ask for) and the shader (which turns it
 * into a mip LOD).
 *
 * ⚠️ This is a FLOOR on the station blur, never a replacement for it — the two
 * answer different questions (how far did the light fall vs. how far has this
 * sample walked from the caster), and `max` is what lets whichever is larger
 * win without either being able to SHARPEN the other. Taking the height term
 * alone would make a long dusk shadow's tip snap crisp; adding them would
 * double-count the near field, where both are already saturated.
 *
 * @param {number} heightPx - this layer's own occluder height.
 * @param {number} [softnessMul=1] - the shared atmospheric softness multiplier
 *   (cloud × night × the author's `softnessBias`).
 * @returns {number} world px, >= 0.
 */
export function layerDiffusionBlurPx(heightPx, softnessMul = 1) {
  const h = Number.isFinite(heightPx) && heightPx > 0 ? heightPx : 0;
  const s = Number.isFinite(softnessMul) && softnessMul > 0 ? softnessMul : 1;
  return h * DIFFUSION_PER_HEIGHT_PX * s;
}

/**
 * THE TIER LADDER. Author, 2026-08-02: *"Ideally, it'll be nice and smooth and
 * reasonable in terms of resolution. I'd rather we had it too high resolution on
 * extreme profile tier so that we can tune from there."* — so Extreme is set
 * deliberately ABOVE where it probably needs to sit, and the tuning direction is
 * DOWN from a picture that is definitely good enough.
 *
 * `layerGridDim` sizes the SILHOUETTE (how crisp a roofline is); `fieldDim` sizes
 * the OUTPUT (how smooth the gradient is). They are separate axes and confusing
 * them was a live bug in the previous model — here they simply move together,
 * because a smear has no reason to resolve one finer than the other.
 *
 * COST, in texture samples per bake (`fieldDim² × (steps + 1)`) — a count, never
 * a millisecond figure, because counts are true on every GPU
 * (`feedback_instruments_must_not_lie`):
 *
 *   0 coarse   512² × 17  ≈    4.5 M
 *   1 standard 1024² × 25 ≈   26 M
 *   2 quality  1536² × 33 ≈   78 M
 *   3 extreme  2048² × 49 ≈  205 M
 *
 * Extreme lands BELOW the model it replaces (~367 M at 1280² × 32 × 7 lateral
 * taps) while carrying twice the silhouette resolution — the lateral tap cone is
 * gone, because one mip-filtered sample per station does the same softening in
 * one fetch instead of seven.
 */
const LAYER_SMEAR_TIER_PLANS = Object.freeze([
  Object.freeze({ fieldDim: 512, layerGridDim: 512, steps: 16, quantizeDeg: 1 }),
  Object.freeze({ fieldDim: 1024, layerGridDim: 1024, steps: 24, quantizeDeg: 0.5 }),
  Object.freeze({ fieldDim: 1536, layerGridDim: 1536, steps: 32, quantizeDeg: 0.5 }),
  Object.freeze({ fieldDim: 2048, layerGridDim: 2048, steps: 48, quantizeDeg: 0.4 }),
]);

/** How many rungs the ladder has (so a status report can say "1 of 3"). */
export const LAYER_SMEAR_MAX_TIER = LAYER_SMEAR_TIER_PLANS.length - 1;

/** The rung a stale/absent tier resolves to, and what `sun-shadow-subsystem.js`
 * constructs at before its first real `maybeBake` (which has not run yet at
 * factory time, so the live profile is not known — see that module's own
 * header). Rung 1 = "soft-cone… TODAY, EXACTLY", matching this ladder's
 * predecessor's own default for the same reason: this is what a player who
 * has never touched the performance setting gets. */
export const LAYER_SMEAR_DEFAULT_TIER = 1;

/**
 * Resolve a rung into the numbers a bake is built from. PURE + TOTAL: a stale,
 * absent or wildly out-of-range tier CLAMPS into the ladder rather than
 * returning `undefined` and building a field of `NaN`.
 *
 * @param {number} tier
 * @returns {{fieldDim:number, layerGridDim:number, steps:number, quantizeDeg:number}}
 */
export function layerSmearTierPlan(tier) {
  const n = Number.isFinite(tier)
    ? Math.max(0, Math.min(LAYER_SMEAR_MAX_TIER, Math.floor(tier)))
    : LAYER_SMEAR_DEFAULT_TIER;
  return LAYER_SMEAR_TIER_PLANS[n];
}

/**
 * Texture samples ONE bake of this plan costs — `fieldDim² × (steps + 1)`, the
 * whole cost model of this effect in one number. Reported rather than converted
 * to milliseconds ON PURPOSE, same reasoning as this ladder's predecessor's own
 * `sunShadowBakeSamples`: a count is true on every GPU, a millisecond figure
 * derived from it is a guess dressed as a measurement
 * (`feedback_instruments_must_not_lie`).
 *
 * @param {{fieldDim: number, steps: number}} plan
 * @returns {number}
 */
export function layerSmearBakeSamples(plan) {
  const dim = Number.isFinite(plan?.fieldDim) && plan.fieldDim > 0 ? plan.fieldDim : 0;
  const steps = Number.isFinite(plan?.steps) && plan.steps > 0 ? plan.steps : 0;
  return dim * dim * (steps + 1);
}

/** A sun this close to straight down throws nothing worth baking. */
const MIN_TAN_ELEV = 1e-4;
/** The same sanity ceiling `sun-occlusion.js#maxThrowPx` uses, for the same
 * reason: a sun ON the horizon must ask for a finite smear, not an infinite one. */
const HARD_CAP_PX = 8192;

const clamp01 = (v) => (v < 0 ? 0 : v > 1 ? 1 : v);

/**
 * How far ONE layer smears: `height / tan(elevation)`, with the same two length
 * controls the previous model exposed (the author's "single control for shadow
 * offset at dawn / dusk" — `sun-occlusion.js#resolveSunMarch` has the full
 * reasoning, and this keeps them behaving identically so the control does not
 * change meaning when the model does).
 *
 * @param {object} args
 * @param {number} args.heightPx - this layer's ONE height, world px. Never
 *   per-texel: a layer is a flat silhouette at a single elevation, which is the
 *   simplification the whole model is built on.
 * @param {number} args.elevationDeg
 * @param {number} [args.lengthScale=1] - global throw multiplier (<1 = shorter).
 * @param {number} [args.maxLengthMul=0] - cap as a multiple of the layer's own
 *   height; 0/absent = uncapped.
 * @returns {number} world px, >= 0.
 */
export function layerThrowPx({ heightPx, elevationDeg, lengthScale = 1, maxLengthMul = 0 }) {
  const h = Number.isFinite(heightPx) && heightPx > 0 ? heightPx : 0;
  if (h === 0) return 0;
  const elev = Math.min(90, Math.max(0, Number.isFinite(elevationDeg) ? elevationDeg : 90));
  const realTan = Math.tan((elev * Math.PI) / 180);
  const scale = Number.isFinite(lengthScale) && lengthScale > 0 ? lengthScale : 1;
  const scaledTan = realTan / scale;
  const tanFloor = Number.isFinite(maxLengthMul) && maxLengthMul > 0 ? 1 / maxLengthMul : 0;
  const effTan = Math.max(scaledTan, tanFloor);
  return Math.min(HARD_CAP_PX, effTan > MIN_TAN_ELEV ? h / effTan : HARD_CAP_PX);
}

/**
 * THE FALLOFF — the one function THE LAW depends on. `(1 − t)^e` on [0,1], zero
 * beyond, so a shadow is fully dark against its caster and gone at the layer's
 * throw distance.
 *
 * ⚠️ MUST BE MONOTONICALLY DECREASING ON [0,1]. That is the sole precondition of
 * this module's monotonicity proof (see the header), and it is asserted directly
 * in the test suite rather than assumed of whatever expression happens to live
 * here. `exponent` is pure LOOK — the author dials it — and any positive value
 * keeps the property, which is exactly why it is safe to expose as a slider.
 *
 * @param {number} t - normalised distance along this layer's throw, 0..1.
 * @param {number} [exponent=1.6]
 * @returns {number} 0..1
 */
export function smearFalloff01(t, exponent = 1.6) {
  if (!(t > 0)) return 1;
  if (t >= 1) return 0;
  const e = Number.isFinite(exponent) && exponent > 0 ? exponent : 1.6;
  return Math.pow(1 - t, e);
}

/**
 * Where station `j` of `n` sits along the smear — `maxThrowPx · (j/n)²`, NOT
 * evenly spaced.
 *
 * Stations bunch toward the caster because that is where the shadow is darkest,
 * where every layer is still active (a short wall's throw ends long before a
 * tall floor's), and where a step of error is most visible. Out at the tip the
 * shadow is faint and heavily blurred, and sparse sampling there costs nothing
 * anyone can see. Even spacing would spend most of its samples on the part of
 * the curve that matters least — and would under-sample any layer whose throw is
 * short relative to the tallest one, which on a real map is most of them.
 *
 * @param {number} j @param {number} n @param {number} maxThrowPx
 * @returns {number} world px from the receiver, along the direction TO the sun.
 */
export function stationDistancePx(j, n, maxThrowPx) {
  const u = n > 0 ? j / n : 0;
  return maxThrowPx * u * u;
}

/**
 * The LOCAL spacing between neighbouring stations at station `j` — the width no
 * sample may be narrower than, or a thin caster falls between two stations and
 * THE LAW breaks discretely even though it holds continuously (see the header).
 *
 * `d(u) = maxThrow·u²` ⇒ `d′(u) = 2·maxThrow·u`, so the spacing at `j` is
 * `2·maxThrow·(j/n)/n`. Returned rather than inlined because the shader needs the
 * identical number and a second derivation is how the two would drift apart.
 *
 * @param {number} j @param {number} n @param {number} maxThrowPx
 * @returns {number} world px
 */
export function stationSpacingPx(j, n, maxThrowPx) {
  if (!(n > 0)) return maxThrowPx;
  return (2 * maxThrowPx * (j / n)) / n;
}

/** How many ring samples approximate the shader's wide-mip isotropic read —
 * same technique, same sample count, as the old contact-AO ring this model's
 * predecessor used (the twin has no texture to blur). */
const DEPTH_RING_SAMPLES = 8;

/**
 * How many NESTED radii the depth term reads. Author, 2026-08-02, on the first
 * version (single radius): *"This is the furthest from the bridge edge and I'd
 * like the middle of this sky reach bit to be darkest and darker."*
 *
 * ONE radius cannot do that. A single isotropic read SATURATES: once a receiver
 * is further from the nearest edge than the blur radius, every sample lands on
 * solid coverage and the term pins at 1 — so the middle of a wide span and a
 * point one radius in from its edge come out IDENTICAL, which is the same
 * flatness the author asked to fix in the first place, just moved inward.
 *
 * Reading several nested radii and averaging fixes it, because depth is then
 * encoded in HOW MANY scales still see solid: a point deep inside is covered at
 * every radius (→ 1), a point near the edge is covered only at the tightest
 * (→ ~1/N). The gradient therefore keeps deepening all the way to the widest
 * radius rather than stopping at the first one — and the widest radius becomes
 * the honest, dial-able answer to "how far in is 'fully enclosed'".
 */
export const DEPTH_SCALES = 3;

/**
 * THE SKY-REACH GRADIENT (2026-08-02). Author, live, on the layer-smear
 * model's first real-map result: *"a soft gradient for the sky reach so that
 * it gets darker as it gets further in which should make the most middle
 * section of the bridge even darker but still a little bit of light should
 * leak through."*
 *
 * The march loop above CANNOT produce this. Its every station reads
 * `S(x,y)` directly at the receiver for `d=0`, so a receiver sitting anywhere
 * inside a solid silhouette (the deck of a wide bridge, say) already gets
 * `coverage·falloff(0) = coverage·1` from its OWN position before marching a
 * single step further — the whole interior of any solid shape saturates to
 * the SAME flat value, with zero regard for how deep in it you are. That is
 * fine, correct even, for a THIN caster like a wall (there is no meaningful
 * "interior" to a wall a receiver could stand inside). It is exactly wrong
 * for a WIDE one: the middle of the bridge and the texel one step in from its
 * edge get identical occlusion, when the whole point of "further in, darker"
 * is that they should not.
 *
 * This is a DIFFERENT physical question from the march's — not "how far have
 * I walked away from a caster's edge" (requirement 2, THE LAW's own
 * territory) but "how deep am I enclosed by this SAME caster's own mass,
 * measured in every direction, not just toward the sun". A wide isotropic
 * blur answers exactly that: near an edge it reads a soft, partial mix of
 * covered and open; deep in a shape wider than the blur radius it reads
 * close to solid, correctly indifferent to going even deeper (which is the
 * "middle of the bridge, but not literally infinite" case the author asked
 * for) — smoothly, with no seam where it hands off to the march term.
 *
 * Folded into the SAME per-layer accumulator as the march stations, via
 * `max` — the identical reasoning `marchVisibilitySmear`'s own header already
 * gives for combining stations WITHIN one occluder: this is still one
 * physical mass, just answered by a second geometric question about it, not
 * a second occluder in series (which is what earns a `×`, not a `max`).
 *
 * "A little light should leak through" needs no separate mechanism: it is
 * `strengths[i] < 1`, already exposed, already load-bearing here as it was
 * before this term existed — even a fully-saturated depth term never reaches
 * pure black once its own layer strength is below 1.
 *
 * @param {(x:number,y:number)=>number[]} sampleLayers
 * @param {number} x @param {number} y @param {number} layerIndex
 * @param {number} radiusPx - 0 disables this layer's gradient entirely (the
 *   default — a wall gets no depth term unless the caller asks for one).
 * @returns {number} 0..1
 */
function isotropicDepthTerm(sampleLayers, x, y, layerIndex, radiusPx) {
  if (!(radiusPx > 0)) return 0;
  const at = (px, py) => clamp01(sampleLayers(px, py)?.[layerIndex] ?? 0);
  let total = 0;
  // Nested radii — see DEPTH_SCALES for why one is not enough. Each scale is
  // its own ring average; the scales are then averaged, so the result is
  // "what fraction of my neighbourhood, across every distance I look, is
  // still solid" — which keeps rising the deeper in you stand.
  for (let s = 1; s <= DEPTH_SCALES; s++) {
    const r = (radiusPx * s) / DEPTH_SCALES;
    let sum = at(x, y);
    let n = 1;
    for (let k = 0; k < DEPTH_RING_SAMPLES; k++) {
      const a = (k / DEPTH_RING_SAMPLES) * Math.PI * 2;
      sum += at(x + Math.cos(a) * r, y + Math.sin(a) * r);
      n++;
    }
    total += sum / n;
  }
  return total / DEPTH_SCALES;
}

/**
 * Resolve everything the smear needs about the sky ONCE per bake, on the CPU, so
 * the twin below and the shader cannot end up with two ideas of where the sun is
 * (the same contract `resolveSunMarch` established, and for the same reason).
 *
 * @param {object} args
 * @param {number} args.azimuthDeg @param {number} args.elevationDeg
 * @param {number[]} args.heightsPx - one height per layer, `SHADOW_LAYER_COUNT` long.
 * @param {number} [args.lengthScale] @param {number} [args.maxLengthMul]
 * @returns {{dirX:number, dirY:number, throwPx:number[], heightPx:number[], maxThrowPx:number}}
 *   `dirX/dirY` point TOWARD the sun — the direction the back-trace walks.
 *   `heightPx` is the resolved INPUT height per layer, carried through beside
 *   the throw it produced: {@link layerDiffusionBlurPx} needs the height
 *   itself, and it is NOT recoverable from `throwPx` (the dawn/dusk cap can
 *   collapse two very different heights onto the same capped throw). Returning
 *   both from the one resolve is what keeps the twin and the shader reading the
 *   same pair, rather than the caller re-deriving one of them.
 */
export function resolveLayerSmear({ azimuthDeg, elevationDeg, heightsPx = [], lengthScale = 1, maxLengthMul = 0 }) {
  const dir = marchDirectionToSun(azimuthDeg);
  const throwPx = [];
  const heightPx = [];
  for (let i = 0; i < SHADOW_LAYER_COUNT; i++) {
    const h = Number.isFinite(heightsPx[i]) && heightsPx[i] > 0 ? heightsPx[i] : 0;
    heightPx.push(h);
    throwPx.push(layerThrowPx({ heightPx: h, elevationDeg, lengthScale, maxLengthMul }));
  }
  return { dirX: dir.x, dirY: dir.y, throwPx, heightPx, maxThrowPx: Math.max(0, ...throwPx) };
}

/**
 * ONE receiver's sun visibility under the layer stack — the CPU twin the shader
 * transcribes.
 *
 * @param {object} args
 * @param {number} args.x @param {number} args.y - the receiver, world px.
 * @param {(x:number, y:number) => (number[]|null)} args.sampleLayers - coverage
 *   0..1 per layer at a world position, `SHADOW_LAYER_COUNT` long. This IS the
 *   RGBA texture read, one channel per layer. Off-map MUST clamp to the edge
 *   rather than return empty — the author's rule: a building whose `_Outdoors`
 *   dark runs off the map keeps casting into the distance.
 * @param {{dirX:number, dirY:number, throwPx:number[], maxThrowPx:number}} args.resolved -
 *   from {@link resolveLayerSmear}.
 * @param {number[]} [args.strengths] - per-layer 0..1. An upper floor need not
 *   darken as hard as a wall (sky blocked from above still leaves horizon
 *   light); defaults to full for every layer until the author dials it.
 * @param {number[]} [args.depthRadiusPx] - per-layer 0..N world px, THE
 *   SKY-REACH GRADIENT ({@link isotropicDepthTerm}'s own header has the full
 *   argument). 0 (the default, every layer) leaves that layer exactly as it
 *   was before this parameter existed — nothing changes unless the caller
 *   asks for it. A layer whose own `heightsPx` is 0 never gets a depth term
 *   regardless of this value: a height-0 layer is OFF, full stop.
 * @param {number} [args.steps=32]
 * @param {number} [args.falloffExp=1.6]
 * @param {number} [args.strength=1] - global look strength.
 * @param {number} [args.receiverGate=1] - 0 switches this texel off entirely.
 * @returns {number} sun visibility 0..1.
 */
export function layerSmearVisibility({
  x,
  y,
  sampleLayers,
  resolved,
  strengths = [],
  depthRadiusPx = [],
  steps = 32,
  falloffExp = 1.6,
  strength = 1,
  receiverGate = 1,
}) {
  const gate = clamp01(receiverGate);
  if (gate <= 0) return 1;
  const maxThrow = resolved?.maxThrowPx ?? 0;
  // No layer reaches anywhere — a sun overhead, or a stack with no heights. Not
  // a degenerate case to guard against, just a fully-lit texel.
  if (!(maxThrow > 0)) return 1;

  const n = Math.max(1, Math.floor(steps));
  const throws = resolved.throwPx;
  const occ = new Array(SHADOW_LAYER_COUNT).fill(0);

  for (let j = 0; j <= n; j++) {
    const d = stationDistancePx(j, n, maxThrow);
    const sx = x + resolved.dirX * d;
    const sy = y + resolved.dirY * d;
    // ONE sample serves every layer WITHOUT a depth radius. They live in
    // different channels of the same texel, so splitting them costs no extra
    // bandwidth — and evaluating each at its OWN normalised distance is what
    // lets a single shared walk carry four different throw lengths.
    const at = sampleLayers(sx, sy);
    for (let i = 0; i < SHADOW_LAYER_COUNT; i++) {
      const L = throws[i];
      if (!(L > 0) || d > L) continue;
      // THE SKY-REACH GRADIENT — see isotropicDepthTerm's own header. NOT a
      // term added alongside the march (a `max` against an already-saturated
      // ceiling is a no-op — measured, not assumed: the first version of this
      // feature did exactly that and a test caught it reading identical
      // values at a shape's centre and its edge). Instead, for a layer with a
      // depth radius, THIS STATION'S OWN coverage read is the isotropic
      // blur, evaluated at THIS station's position — so the near-field read
      // (small `d`, near-`fall=1`) is exactly "how enclosed is the receiver
      // itself", and the far-field stations still carry the normal dawn/dusk
      // elongation via the same `falloff(d/L)` every other layer uses.
      const r = depthRadiusPx[i] ?? 0;
      // ⚠️ THE DEPTH TERM MODULATES THE SILHOUETTE, IT DOES NOT REPLACE IT
      // (2026-08-02, author live: *"Sky reach and building shadows both appear
      // to be heavily blurred, so heavily that they detach from buildings."*).
      //
      // MEASURED, on the author's own real scene: at `skyReachDepthPx = 1300`
      // and a 2048-wide layer texture (5.2 world px per texel), the three
      // nested reads request mip 6.4 / 7.4 / 8.0 — and mip 8 of that texture
      // is EIGHT BY FOUR TEXELS for the entire 10650×4950 map, one texel per
      // 1300×1300 world px. Used as the coverage OUTRIGHT, that wash *was* the
      // shadow's silhouette, so the sky-reach shadow spread ~1300px past any
      // real edge and stopped resembling the thing casting it.
      //
      // Multiplying by the SHARP read restores the silhouette while keeping
      // the gradient: inside the covered span `sharp` is 1 and the depth term
      // still varies (darker the further in, which is the whole feature);
      // outside it `sharp` is 0, so the wash contributes exactly nothing. The
      // directional cast survives because both factors are sampled at the
      // STATION, and stations reach into the caster.
      const sharp = clamp01(at?.[i] ?? 0);
      const coverage = r > 0 ? isotropicDepthTerm(sampleLayers, sx, sy, i, r) * sharp : sharp;
      const term = coverage * smearFalloff01(d / L, falloffExp);
      if (term > occ[i]) occ[i] = term;
    }
  }

  // ⚠️ A LAYER NEVER SHADOWS ITS OWN FOOTPRINT (author, live 2026-08-02: *"a
  // shadow which is created by a tile with elevation is being composited on
  // top of the thing that is creating it. It should be underneath."*).
  //
  // Foundry elevation is a SORT KEY, not a spatial offset (memory:
  // feedback_elevation_is_sort_key_not_offset) — a raised tile's sprite
  // occupies the very same (x,y) as the ground it is "above". So at a texel
  // where a layer's own coverage is 1, the pixel you can SEE *is* that
  // layer's own caster, and station 0 (`d = 0`, `fall = 1`) hands it its own
  // coverage as a full-strength shadow. It darkens itself.
  //
  // BOTH walls and overhead are excluded; the floor-above/higher layers are
  // NOT, and THAT is the asymmetry that matters:
  //   - walls — the receiver IS the wall. Exclude.
  //   - overhead — the receiver IS the caster. Exclude.
  //   - the floor above / higher — the receiver is genuinely BENEATH the
  //     caster, on different art. Excluding those would delete the sky-reach
  //     shadow (the bridge deck darkening the water) outright, which is the
  //     one thing this model most exists to draw.
  //
  // ⚠️ WALLS WAS ORIGINALLY LEFT OUT ON PURPOSE, and the reasoning was wrong.
  // The original argument: "the receiver IS the wall, and `gate` (the
  // sharpened `_Outdoors` read) already removes it, so nothing more is
  // needed." That is true only for a texel `gate` actually shuts off — one
  // that reads UNAMBIGUOUSLY indoors. Author, 2026-08-03, live, on a
  // thatched roof: a dark band sat directly on the ridge line, self-cast.
  // Measured with the mask-stack probe: the ridge is an ANTIALIASED edge in
  // the roof's own `_Outdoors` art — walls-coverage ≈0.51, not 0 or 1.
  // `1 − 0.51 = 0.49` clears `gate`'s own smoothstep threshold, so `gate`
  // reads the texel as "outdoors enough" and lets its shadow through in
  // full — while that SAME 0.51 walls-coverage still hands station 0 of the
  // march a genuine, undischarged self-occlusion, because nothing was ever
  // excluding it. `gate` and self-exclusion answer different questions —
  // *is this texel outdoors at all* vs. *does this texel's own mass shadow
  // itself* — and a partially-covered boundary texel is exactly the point
  // where only one of the two was ever being asked.
  const selfCoverageWalls = clamp01(sampleLayers(x, y)?.[LAYER_WALLS] ?? 0);
  occ[LAYER_WALLS] *= 1 - selfCoverageWalls;
  const selfCoverage = clamp01(sampleLayers(x, y)?.[LAYER_OVERHEAD] ?? 0);
  occ[LAYER_OVERHEAD] *= 1 - selfCoverage;

  // Transmittances multiply. `strength · gate` scales each factor rather than
  // the product, so a strength of 0 returns exactly 1 no matter how many layers
  // are stacked.
  const global = clamp01(strength) * gate;
  let transmittance = 1;
  transmittance *= 1 - occ[LAYER_WALLS] * clamp01(strengths[LAYER_WALLS] ?? 1) * global;
  transmittance *= 1 - occ[LAYER_OVERHEAD] * clamp01(strengths[LAYER_OVERHEAD] ?? 1) * global;

  // ⚠️ THE BANDS COMBINE BY `max`, NOT BY `×` (2026-08-05, the shadow cascade).
  // Everything else in this model multiplies, and the header's argument for
  // that is right — a wall beside you and a deck above you are different
  // occluders in series, and light must clear both. The bands are NOT that.
  // They are ONE physical stack sliced at two elevations, and by construction
  // they are NESTED (`coverAbove(F+1) ⊆ coverAbove(F)` — `shadow-bands.js`'s
  // own header) — so at any texel where the taller band is present, the
  // shorter one is present too, describing the SAME masonry. Multiplying them
  // would double-darken every multi-storey building against a single-storey
  // one, and would keep darkening further with every floor added: a five-storey
  // tower's shadow would go blacker than a three-storey one's for no physical
  // reason, and "a little light should leak through" (the author's own rule,
  // and what `SUN_SHADOW_LAYER_STRENGTH < 1` exists to guarantee) would quietly
  // stop being true as scenes got taller.
  //
  // `max` is also the same combiner this model already uses WITHIN a layer, for
  // exactly the same reason stated in the header: those samples are one
  // occluder seen from many distances, a union. The bands are one occluder
  // seen at many elevations. Same physics, same operator.
  //
  // For a two-floor scene band 1's throw is 0, so its occlusion is 0, so this
  // reduces to `1 − occ[band0]·s·global` — BYTE-IDENTICAL to what the previous
  // single-"above"-layer model computed. The cascade adds length to tall
  // stacks without touching the picture on short ones.
  let bandOcc = 0;
  for (const i of SHADOW_BAND_LAYER_INDICES) {
    const scaled = occ[i] * clamp01(strengths[i] ?? 1);
    if (scaled > bandOcc) bandOcc = scaled;
  }
  transmittance *= 1 - bandOcc * global;
  return clamp01(transmittance);
}
