/**
 * @fileoverview Contextual Scene Grade — params + Tweakpane schema (no GPU render).
 * @module compositor-v2/effects/ContextualSceneGradeEffectV2
 */

import { CONTEXT_GRADE_EASING_IDS } from '../../core/context-grade/context-grade-spec.js';

/** @param {string} prefix @param {string} label */
const packSlider = (prefix, label, key, min, max, step, defaultVal, tooltip) => ({
  type: 'slider',
  min,
  max,
  step,
  default: defaultVal,
  label: `${label} ${key.replace(/^[a-z]/, (c) => c.toUpperCase())}`,
  tooltip,
});

/** @returns {Record<string, object>} */
function buildPackParameters(prefix, label, defaults) {
  return {
    [`${prefix}Exposure`]: packSlider(prefix, label, 'exposure', -2, 2, 0.01, defaults.exposure, 'Additive exposure stops when this context is active.'),
    [`${prefix}Saturation`]: packSlider(prefix, label, 'saturation', -1, 1, 0.01, defaults.saturation, 'Saturation delta from neutral (0 = unchanged).'),
    [`${prefix}Brightness`]: packSlider(prefix, label, 'brightness', -0.5, 0.5, 0.01, defaults.brightness, 'Brightness offset.'),
    [`${prefix}Contrast`]: packSlider(prefix, label, 'contrast', -1, 1, 0.01, defaults.contrast, 'Contrast delta from 1.0.'),
    [`${prefix}Vibrance`]: packSlider(prefix, label, 'vibrance', -1, 1, 0.01, defaults.vibrance, 'Vibrance offset.'),
    [`${prefix}Temperature`]: packSlider(prefix, label, 'temperature', -0.5, 0.5, 0.01, defaults.temperature, 'White-balance temperature offset.'),
    [`${prefix}Tint`]: packSlider(prefix, label, 'tint', -0.5, 0.5, 0.01, defaults.tint, 'White-balance tint offset.'),
    [`${prefix}VignetteStrength`]: packSlider(prefix, label, 'vignetteStrength', -0.25, 0.75, 0.01, defaults.vignetteStrength, 'Contextual edge darkening when this trigger is active. Negative values lighten edges (e.g. window-lit). Stacks additively across triggers.'),
    [`${prefix}MasterGamma`]: packSlider(prefix, label, 'masterGamma', -1, 1, 0.01, defaults.masterGamma, 'Gamma delta from neutral.'),
  };
}

/** @returns {Record<string, number>} */
function modifierDefaults(prefix, values) {
  const out = {};
  for (const [key, val] of Object.entries(values)) {
    const cap = key.charAt(0).toUpperCase() + key.slice(1);
    out[`${prefix}${cap}`] = val;
  }
  return out;
}

const GRADE_VALUE_SUFFIXES = Object.freeze([
  'Exposure', 'Saturation', 'Brightness', 'Contrast', 'Vibrance',
  'Temperature', 'Tint', 'VignetteStrength', 'MasterGamma',
]);

const INTENSITY_SCALE_KEYS = Object.freeze([
  'dramaStrength',
  'dramaPeakExposure', 'dramaPeakBrightness', 'dramaPeakSaturation', 'dramaPeakVibrance',
  'dramaPeakContrast', 'dramaPeakTemperature', 'dramaPeakVignetteLift', 'dramaPeakGammaLift',
  'modOutdoorOvercastWeight', 'modCloudShadowWeight', 'modCanopyWeight', 'modWindowLitBlend',
  'modBuildingShadowWeight', 'modPaintedShadowWeight', 'modTreeDappleWeight',
  'modTreeDappleStrength', 'coherenceAtmosphereScale', 'contextSpatialStrength',
]);

/**
 * Full cinematic reference — scaled by intensity tier presets.
 * @param {number} factor
 * @returns {Record<string, *>}
 */
function buildIntensityPreset(factor) {
  /** @type {Record<string, *>} */
  const ref = {
    enabled: true,
    probeIntervalSec: 5,
    fadeInMs: 9600,
    fadeOutMs: 15600,
    modifierFadeMs: 9600,
    coverShadowFadeMs: 3000,
    easingIn: 'smooth',
    easingOut: 'easeOut',
    dramaEnabled: true,
    dramaStrength: 1.15,
    dramaPeakExposure: 1.05,
    dramaPeakBrightness: 0.05,
    dramaPeakSaturation: 0.14,
    dramaPeakVibrance: 0.18,
    dramaPeakContrast: 0.05,
    dramaPeakTemperature: 0.14,
    dramaPeakVignetteLift: 0.1,
    dramaPeakGammaLift: 0.05,
    dramaPeakAt: 0.28,
    dramaPeakWidth: 0.3,
    dramaSettleDelay: 0.42,
    dramaSettleEasing: 'easeOut',
    envModifiersEnabled: true,
    envModifiersLerpMs: 250,
    contextSpatialEnabled: true,
    contextSpatialStrength: 0.72,
    coherenceEnabled: true,
    coherenceAtmosphereScale: 0.6,
    coherenceMaxExposure: 1.35,
    dazzleContextGradeGate: 0.45,
    eyeAdaptationEnabled: true,
    eyeAdaptationSec: 60,
    coverShadowEyeAdaptationSec: 3,
    eyeAdaptationEasing: 'easeOut',
    outdoorFadeInMs: 3800,
    outdoorFadeOutMs: 4800,
    outdoorEasingIn: 'smooth',
    outdoorExposure: 0.34,
    outdoorSaturation: 0.06,
    outdoorBrightness: 0,
    outdoorContrast: 0.02,
    outdoorVibrance: 0.1,
    outdoorTemperature: 0.08,
    outdoorTint: 0,
    outdoorVignetteStrength: 0,
    outdoorMasterGamma: 0,
    indoorFadeInMs: 2800,
    indoorFadeOutMs: 5600,
    indoorEasingIn: 'exp',
    indoorEasingOut: 'easeOut',
    indoorExposure: -0.52,
    indoorSaturation: -0.16,
    indoorBrightness: -0.02,
    indoorContrast: -0.02,
    indoorVibrance: -0.1,
    indoorTemperature: -0.02,
    indoorTint: 0,
    indoorVignetteStrength: 0.32,
    indoorMasterGamma: 0.1,
    modOutdoorOvercastWeight: 1,
    modCloudShadowWeight: 1,
    modCanopyWeight: 1,
    modWindowLitBlend: 0.65,
    modBuildingShadowWeight: 1,
    modPaintedShadowWeight: 1,
    modTreeDappleWeight: 1,
    modOutdoorOvercastExposure: -0.05,
    modOutdoorOvercastSaturation: -0.06,
    modCloudShadowExposure: -0.16,
    modCloudShadowTemperature: -0.08,
    modCanopyExposure: -0.12,
    modCanopyTemperature: -0.03,
    modWindowLitExposure: 0.14,
    modWindowLitTemperature: 0.06,
    modBuildingShadowExposure: -0.4,
    modBuildingShadowSaturation: -0.05,
    modBuildingShadowContrast: 0.05,
    modBuildingShadowVibrance: -0.03,
    modBuildingShadowVignetteStrength: 0.08,
    modPaintedShadowExposure: -0.18,
    modTreeDappleExposure: -0.06,
    modTreeDappleSaturation: -0.02,
    modTreeDappleVibrance: 0.03,
    modTreeDappleTemperature: -0.02,
    modTreeDappleStrength: 0.72,
    modTreeDappleScale: 42,
    modTreeDappleGreenR: 0.86,
    modTreeDappleGreenG: 1.06,
    modTreeDappleGreenB: 0.82,
    envOvercastExposure: -0.06,
    envOvercastSaturation: -0.08,
    envStormExposure: -0.12,
    envStormSaturation: -0.12,
    envNightExposure: -0.1,
    envTwilightExposure: -0.04,
    envDarknessExposure: -0.08,
  };

  if (factor === 1) return { ...ref };

  /** @type {Record<string, *>} */
  const out = { ...ref };
  for (const [key, val] of Object.entries(ref)) {
    if (typeof val !== 'number') continue;
    if (INTENSITY_SCALE_KEYS.includes(key) || GRADE_VALUE_SUFFIXES.some((s) => key.endsWith(s))) {
      out[key] = val * factor;
    }
  }
  return out;
}

export class ContextualSceneGradeEffectV2 {
  constructor() {
    this.params = ContextualSceneGradeEffectV2.createDefaultParams();
  }

  static createDefaultParams() {
    return {
      enabled: true,

      probeIntervalSec: 5,
      moveGateGrid: 0,
      outdoorThresholdHigh: 0.82,
      indoorThresholdLow: 0.18,

      fadeInMs: 3600,
      fadeOutMs: 7200,
      easingIn: 'smooth',
      easingOut: 'easeOut',

      modifierFadeMs: 3600,
      coverShadowFadeMs: 3000,

      dramaEnabled: true,
      dramaRequireDaylight: true,
      dramaStrength: 1,
      dramaPeakExposure: 0.85,
      dramaPeakBrightness: 0.04,
      dramaPeakSaturation: 0.12,
      dramaPeakVibrance: 0.14,
      dramaPeakContrast: 0.05,
      dramaPeakTemperature: 0.1,
      dramaPeakVignetteLift: 0.1,
      dramaPeakGammaLift: 0.05,
      dramaPeakAt: 0.3,
      dramaPeakWidth: 0.26,
      dramaSettleDelay: 0.38,
      dramaSettleEasing: 'easeOut',

      outdoorFadeInMs: 0,
      outdoorFadeOutMs: 0,
      outdoorEasingIn: '',
      outdoorEasingOut: '',

      indoorFadeInMs: 0,
      indoorFadeOutMs: 0,
      indoorEasingIn: '',
      indoorEasingOut: '',

      eyeAdaptationEnabled: true,
      eyeAdaptationSec: 60,
      coverShadowEyeAdaptationSec: 3,
      eyeAdaptationEasing: 'easeOut',

      outdoorExposure: 0.18,
      outdoorSaturation: 0.04,
      outdoorBrightness: 0,
      outdoorContrast: 0.02,
      outdoorVibrance: 0.05,
      outdoorTemperature: 0.04,
      outdoorTint: 0,
      outdoorVignetteStrength: 0,
      outdoorMasterGamma: 0,

      indoorExposure: -0.42,
      indoorSaturation: -0.1,
      indoorBrightness: -0.02,
      indoorContrast: -0.02,
      indoorVibrance: -0.05,
      indoorTemperature: -0.02,
      indoorTint: 0,
      indoorVignetteStrength: 0.22,
      indoorMasterGamma: 0.06,

      envModifiersEnabled: true,
      envModifiersLerpMs: 250,
      envStormThreshold: 0.55,
      envOvercastThreshold: 0.35,
      envClearThreshold: 0.18,
      envNightThreshold: 0.22,
      envDayThreshold: 0.62,
      envDarknessHeavyThreshold: 0.72,
      envDarknessNormalThreshold: 0.55,
      ...modifierDefaults('envOvercast', {
        exposure: -0.06,
        saturation: -0.08,
        brightness: 0.02,
        contrast: -0.04,
        vibrance: -0.05,
        temperature: -0.04,
        tint: 0,
        vignetteStrength: 0,
        masterGamma: 0.02,
      }),
      ...modifierDefaults('envStorm', {
        exposure: -0.12,
        saturation: -0.12,
        brightness: -0.02,
        contrast: -0.06,
        vibrance: -0.08,
        temperature: -0.06,
        tint: 0.02,
        vignetteStrength: 0.06,
        masterGamma: 0.04,
      }),
      ...modifierDefaults('envNight', {
        exposure: -0.1,
        saturation: -0.06,
        brightness: -0.03,
        contrast: 0,
        vibrance: -0.04,
        temperature: -0.05,
        tint: 0,
        vignetteStrength: 0.24,
        masterGamma: 0.05,
      }),
      ...modifierDefaults('envTwilight', {
        exposure: -0.04,
        saturation: -0.03,
        brightness: 0,
        contrast: 0,
        vibrance: 0,
        temperature: 0.03,
        tint: 0,
        vignetteStrength: 0.1,
        masterGamma: 0.02,
      }),
      ...modifierDefaults('envDarkness', {
        exposure: -0.08,
        saturation: -0.05,
        brightness: -0.02,
        contrast: 0.02,
        vibrance: -0.03,
        temperature: -0.02,
        tint: 0,
        vignetteStrength: 0.18,
        masterGamma: 0.06,
      }),

      cloudShadowThresholdLow: 0.42,
      cloudShadowThresholdHigh: 0.62,
      canopyShadedThreshold: 0.38,
      canopyOpenThreshold: 0.58,
      modOutdoorOvercastWeight: 1,
      modCloudShadowWeight: 1,
      modCanopyWeight: 1,
      modWindowLitBlend: 0.65,
      modBuildingShadowWeight: 1,
      modPaintedShadowWeight: 1,
      modTreeDappleWeight: 1,
      buildingShadowSensitivity: 75,
      buildingShadowProbeFootprint: 1,
      buildingShadowPartialDetect: true,
      buildingShadowUseAdvancedThresholds: false,
      buildingShadowLitLow: 0.88,
      buildingShadowLitHigh: 0.94,
      paintedShadowLitLow: 0.85,
      paintedShadowLitHigh: 0.94,
      treeShadowLitLow: 0.93,
      treeShadowLitHigh: 0.98,
      treeDappleDayThreshold: 0.35,
      ...modifierDefaults('modBuildingShadow', {
        exposure: -0.4,
        saturation: -0.05,
        brightness: -0.02,
        contrast: 0.05,
        vibrance: -0.03,
        temperature: -0.02,
        tint: 0,
        vignetteStrength: 0.08,
        masterGamma: 0.04,
      }),
      ...modifierDefaults('modPaintedShadow', {
        exposure: -0.18,
        saturation: 0,
        brightness: 0,
        contrast: 0,
        vibrance: 0,
        temperature: 0,
        tint: 0,
        vignetteStrength: 0,
        masterGamma: 0,
      }),
      ...modifierDefaults('modTreeDapple', {
        exposure: -0.06,
        saturation: -0.02,
        brightness: 0,
        contrast: 0,
        vibrance: 0.03,
        temperature: -0.02,
        tint: 0,
        vignetteStrength: 0,
        masterGamma: 0,
      }),
      modTreeDappleStrength: 0.72,
      modTreeDappleScale: 42,
      modTreeDappleGreenR: 0.86,
      modTreeDappleGreenG: 1.06,
      modTreeDappleGreenB: 0.82,

      ...modifierDefaults('modOutdoorOvercast', {
        exposure: -0.05,
        saturation: -0.06,
        brightness: 0.01,
        contrast: -0.03,
        vibrance: -0.04,
        temperature: -0.03,
        tint: 0,
        vignetteStrength: 0,
        masterGamma: 0,
      }),
      ...modifierDefaults('modCloudShadow', {
        exposure: -0.14,
        saturation: -0.05,
        brightness: -0.03,
        contrast: -0.02,
        vibrance: -0.03,
        temperature: -0.08,
        tint: 0,
        vignetteStrength: 0,
        masterGamma: 0.02,
      }),
      ...modifierDefaults('modCanopy', {
        exposure: -0.1,
        saturation: -0.04,
        brightness: -0.02,
        contrast: -0.02,
        vibrance: 0.02,
        temperature: -0.03,
        tint: 0.01,
        vignetteStrength: 0.04,
        masterGamma: 0.03,
      }),
      ...modifierDefaults('modWindowLit', {
        exposure: 0.12,
        saturation: 0.04,
        brightness: 0.05,
        contrast: 0.02,
        vibrance: 0.03,
        temperature: 0.06,
        tint: 0,
        vignetteStrength: -0.08,
        masterGamma: -0.03,
      }),

      coherenceEnabled: true,
      coherenceAtmosphereScale: 0.6,
      coherenceMaxExposure: 1.35,
      coherenceMaxVignette: 0.55,
      contextVignetteSoftness: 0.55,
      contextVignetteInner: 0.42,
      dazzleContextGradeGate: 0.45,
      contextSpatialEnabled: true,
      contextSpatialStrength: 0.72,

      statusSubject: '(none)',
      statusProbeAge: '—',
      statusOutdoorsSample: '—',
      statusIndoorOutdoor: 'Unknown',
      statusState: 'Idle',
      statusMaskProbe: '—',
      statusCcOverlay: 'Off',
      statusSkyCondition: '—',
      statusDayPhase: '—',
      statusContextKey: '—',
      statusCoverShadow: '—',
      statusEyeAdaptation: '—',
    };
  }

  static getControlSchema() {
    const outdoorPack = buildPackParameters('outdoor', 'Outdoor', {
      exposure: 0.18,
      saturation: 0.04,
      brightness: 0,
      contrast: 0.02,
      vibrance: 0.05,
      temperature: 0.04,
      tint: 0,
      vignetteStrength: 0,
      masterGamma: 0,
    });

    const indoorPack = buildPackParameters('indoor', 'Indoor', {
      exposure: -0.38,
      saturation: -0.1,
      brightness: -0.04,
      contrast: -0.02,
      vibrance: -0.05,
      temperature: -0.02,
      tint: 0,
      vignetteStrength: 0.22,
      masterGamma: 0.06,
    });

    const envOvercastPack = buildPackParameters('envOvercast', 'Overcast', {
      exposure: -0.06, saturation: -0.08, brightness: 0.02, contrast: -0.04,
      vibrance: -0.05, temperature: -0.04, tint: 0, vignetteStrength: 0, masterGamma: 0.02,
    });
    const envStormPack = buildPackParameters('envStorm', 'Storm', {
      exposure: -0.12, saturation: -0.12, brightness: -0.02, contrast: -0.06,
      vibrance: -0.08, temperature: -0.06, tint: 0.02, vignetteStrength: 0.06, masterGamma: 0.04,
    });
    const envNightPack = buildPackParameters('envNight', 'Night', {
      exposure: -0.1, saturation: -0.06, brightness: -0.03, contrast: 0,
      vibrance: -0.04, temperature: -0.05, tint: 0, vignetteStrength: 0.24, masterGamma: 0.05,
    });
    const envTwilightPack = buildPackParameters('envTwilight', 'Twilight', {
      exposure: -0.04, saturation: -0.03, brightness: 0, contrast: 0,
      vibrance: 0, temperature: 0.03, tint: 0, vignetteStrength: 0.1, masterGamma: 0.02,
    });
    const envDarknessPack = buildPackParameters('envDarkness', 'Darkness', {
      exposure: -0.08, saturation: -0.05, brightness: -0.02, contrast: 0.02,
      vibrance: -0.03, temperature: -0.02, tint: 0, vignetteStrength: 0.18, masterGamma: 0.06,
    });
    const modOutdoorOvercastPack = buildPackParameters('modOutdoorOvercast', 'Outdoor overcast', {
      exposure: -0.05, saturation: -0.06, brightness: 0.01, contrast: -0.03,
      vibrance: -0.04, temperature: -0.03, tint: 0, vignetteStrength: 0, masterGamma: 0,
    });
    const modCloudShadowPack = buildPackParameters('modCloudShadow', 'Cloud shadow', {
      exposure: -0.14, saturation: -0.05, brightness: -0.03, contrast: -0.02,
      vibrance: -0.03, temperature: -0.08, tint: 0, vignetteStrength: 0, masterGamma: 0.02,
    });
    const modCanopyPack = buildPackParameters('modCanopy', 'Canopy', {
      exposure: -0.1, saturation: -0.04, brightness: -0.02, contrast: -0.02,
      vibrance: 0.02, temperature: -0.03, tint: 0.01, vignetteStrength: 0.04, masterGamma: 0.03,
    });
    const modWindowLitPack = buildPackParameters('modWindowLit', 'Window-lit', {
      exposure: 0.12, saturation: 0.04, brightness: 0.05, contrast: 0.02,
      vibrance: 0.03, temperature: 0.06, tint: 0, vignetteStrength: -0.08, masterGamma: -0.03,
    });
    const modBuildingShadowPack = buildPackParameters('modBuildingShadow', 'Building shadow', {
      exposure: -0.4, saturation: -0.05, brightness: -0.02, contrast: 0.05,
      vibrance: -0.03, temperature: -0.02, tint: 0, vignetteStrength: 0.08, masterGamma: 0.04,
    });
    const modPaintedShadowPack = buildPackParameters('modPaintedShadow', 'Painted shadow', {
      exposure: -0.18, saturation: 0, brightness: 0, contrast: 0,
      vibrance: 0, temperature: 0, tint: 0, vignetteStrength: 0, masterGamma: 0,
    });
    const modTreeDapplePack = buildPackParameters('modTreeDapple', 'Tree dapple (uniform)', {
      exposure: -0.06, saturation: -0.02, brightness: 0, contrast: 0,
      vibrance: 0.03, temperature: -0.02, tint: 0, vignetteStrength: 0, masterGamma: 0,
    });

    const easingOptions = CONTEXT_GRADE_EASING_IDS.reduce((acc, id) => {
      acc[id] = id;
      return acc;
    }, {});

    return {
      enabled: true,
      presetApplyDefaults: true,
      help: {
        title: 'Contextual Scene Grade',
        summary: [
          'Probes update intended grade targets each step; the engine morphs the live CC toward those targets every frame (no per-step transition restarts).',
          'Indoor/outdoor uses a smooth _Outdoors weight blend at doorways — not a hard flip per grid square.',
          'Tier 1: global weather/time env modifiers. Tier 2: cloud shadow, canopy, window-lit, building/painted/tree cover shadows.',
          'Tree dapple at daytime uses a procedural leaf-noise pass in Color Correction (green tint + chunky light patches).',
          'Tier 3: spatial blend at doorways + atmosphere/dazzle coherence with existing CC stack.',
          'Vignette: each trigger pack can add edge darkening; night and indoor defaults are tuned for stronger corners. Shape is controlled globally in the Vignette folder.',
          'Eye adaptation: after settling, each layer (indoor/outdoor base + shadow/modifier stack) fades toward neutral over ~60s — including building and painted shadow.',
          'Outdoor/indoor packs favor exposure over brightness (avoids washed pale mids).',
          'Presets scale the full logic set by intensity — Extreme, Cinematic, Moderate, Mild.',
          'Per-client: each player\'s view follows their own token. GM uses the selected token (sticky last selection).',
        ].join('\n\n'),
      },
      groups: [
        {
          name: 'engine',
          label: 'Engine',
          type: 'folder',
          expanded: true,
          parameters: [
            'probeIntervalSec',
            'moveGateGrid',
            'outdoorThresholdHigh',
            'indoorThresholdLow',
            'fadeInMs',
            'fadeOutMs',
            'modifierFadeMs',
            'coverShadowFadeMs',
            'easingIn',
            'easingOut',
            'eyeAdaptationEnabled',
            'eyeAdaptationSec',
            'coverShadowEyeAdaptationSec',
            'eyeAdaptationEasing',
          ],
        },
        {
          name: 'drama',
          label: 'Transition drama',
          type: 'folder',
          expanded: false,
          parameters: [
            'dramaEnabled',
            'dramaRequireDaylight',
            'dramaStrength',
            'dramaPeakExposure',
            'dramaPeakBrightness',
            'dramaPeakSaturation',
            'dramaPeakVibrance',
            'dramaPeakVignetteLift',
            'dramaPeakAt',
            'dramaPeakWidth',
            'dramaSettleDelay',
            'dramaSettleEasing',
          ],
        },
        {
          name: 'env-modifiers',
          label: 'Environment modifiers',
          type: 'folder',
          expanded: false,
          parameters: [
            'envModifiersEnabled',
            'envModifiersLerpMs',
            'envStormThreshold',
            'envOvercastThreshold',
            'envNightThreshold',
            'envDayThreshold',
            'envDarknessHeavyThreshold',
          ],
        },
        {
          name: 'building-shadow-detect',
          label: 'Building shadow detection',
          type: 'folder',
          expanded: false,
          parameters: [
            'buildingShadowSensitivity',
            'buildingShadowProbeFootprint',
            'buildingShadowPartialDetect',
            'buildingShadowUseAdvancedThresholds',
            'buildingShadowLitLow',
            'buildingShadowLitHigh',
          ],
        },
        {
          name: 'token-modifiers',
          label: 'Token modifiers',
          type: 'folder',
          expanded: false,
          parameters: [
            'cloudShadowThresholdLow',
            'cloudShadowThresholdHigh',
            'canopyShadedThreshold',
            'canopyOpenThreshold',
            'paintedShadowLitLow',
            'paintedShadowLitHigh',
            'treeShadowLitLow',
            'treeShadowLitHigh',
            'treeDappleDayThreshold',
            'modOutdoorOvercastWeight',
            'modCloudShadowWeight',
            'modCanopyWeight',
            'modWindowLitBlend',
            'modBuildingShadowWeight',
            'modPaintedShadowWeight',
            'modTreeDappleWeight',
            'modTreeDappleStrength',
            'modTreeDappleScale',
            'modTreeDappleGreenR',
            'modTreeDappleGreenG',
            'modTreeDappleGreenB',
          ],
        },
        {
          name: 'vignette',
          label: 'Vignette',
          type: 'folder',
          expanded: false,
          parameters: [
            'contextVignetteInner',
            'contextVignetteSoftness',
            'coherenceMaxVignette',
          ],
        },
        {
          name: 'coherence',
          label: 'Stack coherence',
          type: 'folder',
          expanded: false,
          parameters: [
            'coherenceEnabled',
            'coherenceAtmosphereScale',
            'coherenceMaxExposure',
            'dazzleContextGradeGate',
            'contextSpatialEnabled',
            'contextSpatialStrength',
          ],
        },
        {
          name: 'status',
          label: 'Status',
          type: 'folder',
          expanded: true,
          parameters: [
            'statusIndoorOutdoor',
            'statusState',
            'statusContextKey',
            'statusCoverShadow',
            'statusEyeAdaptation',
            'statusSkyCondition',
            'statusDayPhase',
            'statusSubject',
            'statusOutdoorsSample',
            'statusMaskProbe',
            'statusCcOverlay',
            'statusProbeAge',
          ],
        },
        {
          name: 'outdoor-pack',
          label: 'Outdoor pack',
          type: 'folder',
          expanded: false,
          parameters: [
            'outdoorExposure',
            'outdoorSaturation',
            'outdoorBrightness',
            'outdoorContrast',
            'outdoorVibrance',
            'outdoorTemperature',
            'outdoorTint',
            'outdoorVignetteStrength',
            'outdoorMasterGamma',
            'outdoorFadeInMs',
            'outdoorFadeOutMs',
            'outdoorEasingIn',
            'outdoorEasingOut',
          ],
        },
        {
          name: 'indoor-pack',
          label: 'Indoor pack',
          type: 'folder',
          expanded: true,
          parameters: [
            'indoorExposure',
            'indoorSaturation',
            'indoorBrightness',
            'indoorContrast',
            'indoorVibrance',
            'indoorTemperature',
            'indoorTint',
            'indoorVignetteStrength',
            'indoorMasterGamma',
            'indoorFadeInMs',
            'indoorFadeOutMs',
            'indoorEasingIn',
            'indoorEasingOut',
          ],
        },
        {
          name: 'env-overcast-pack',
          label: 'Env — Overcast',
          type: 'folder',
          expanded: false,
          parameters: Object.keys(envOvercastPack),
        },
        {
          name: 'env-storm-pack',
          label: 'Env — Storm',
          type: 'folder',
          expanded: false,
          parameters: Object.keys(envStormPack),
        },
        {
          name: 'env-night-pack',
          label: 'Env — Night',
          type: 'folder',
          expanded: false,
          parameters: Object.keys(envNightPack),
        },
        {
          name: 'env-twilight-pack',
          label: 'Env — Twilight',
          type: 'folder',
          expanded: false,
          parameters: Object.keys(envTwilightPack),
        },
        {
          name: 'env-darkness-pack',
          label: 'Env — Darkness',
          type: 'folder',
          expanded: false,
          parameters: Object.keys(envDarknessPack),
        },
        {
          name: 'mod-outdoor-overcast',
          label: 'Mod — Outdoor overcast',
          type: 'folder',
          expanded: false,
          parameters: Object.keys(modOutdoorOvercastPack),
        },
        {
          name: 'mod-cloud-shadow',
          label: 'Mod — Cloud shadow',
          type: 'folder',
          expanded: false,
          parameters: Object.keys(modCloudShadowPack),
        },
        {
          name: 'mod-canopy',
          label: 'Mod — Canopy',
          type: 'folder',
          expanded: false,
          parameters: Object.keys(modCanopyPack),
        },
        {
          name: 'mod-window-lit',
          label: 'Mod — Window-lit',
          type: 'folder',
          expanded: false,
          parameters: Object.keys(modWindowLitPack),
        },
        {
          name: 'mod-building-shadow',
          label: 'Mod — Building shadow',
          type: 'folder',
          expanded: false,
          parameters: Object.keys(modBuildingShadowPack),
        },
        {
          name: 'mod-painted-shadow',
          label: 'Mod — Painted shadow',
          type: 'folder',
          expanded: false,
          parameters: Object.keys(modPaintedShadowPack),
        },
        {
          name: 'mod-tree-dapple',
          label: 'Mod — Tree dapple',
          type: 'folder',
          expanded: false,
          parameters: Object.keys(modTreeDapplePack),
        },
      ],
      parameters: {
        enabled: { type: 'boolean', default: true, label: 'Enabled' },

        probeIntervalSec: {
          type: 'slider',
          min: 1,
          max: 15,
          step: 0.5,
          default: 5,
          label: 'Probe interval (s)',
          tooltip: 'Minimum time between outdoors mask samples when the token has not moved much.',
        },
        moveGateGrid: {
          type: 'slider',
          min: 0,
          max: 200,
          step: 1,
          default: 0,
          label: 'Move gate (px)',
          tooltip: 'Skip timer probes until the token moves this many scene pixels. 0 = half a grid square.',
        },
        outdoorThresholdHigh: {
          type: 'slider',
          min: 0.5,
          max: 1,
          step: 0.01,
          default: 0.82,
          label: 'Outdoor threshold',
          tooltip: 'Outdoors sample must reach this value to classify as outdoor.',
        },
        indoorThresholdLow: {
          type: 'slider',
          min: 0,
          max: 0.5,
          step: 0.01,
          default: 0.18,
          label: 'Indoor threshold',
          tooltip: 'Outdoors sample at or below this value classifies as indoor.',
        },
        fadeInMs: {
          type: 'slider',
          min: 0,
          max: 30000,
          step: 50,
          default: 3600,
          label: 'Fade in (ms)',
          tooltip: 'Duration when entering indoor/outdoor (base layer). Default is 3× the original 1.2s.',
        },
        fadeOutMs: {
          type: 'slider',
          min: 0,
          max: 30000,
          step: 50,
          default: 7200,
          label: 'Fade out (ms)',
          tooltip: 'Duration when returning to neutral or leaving a context (base layer).',
        },
        modifierFadeMs: {
          type: 'slider',
          min: 0,
          max: 30000,
          step: 50,
          default: 3600,
          label: 'Modifier fade (ms)',
          tooltip: 'Cloud, canopy, and other token modifier cross-fades (modifier layer).',
        },
        coverShadowFadeMs: {
          type: 'slider',
          min: 0,
          max: 30000,
          step: 50,
          default: 3000,
          label: 'Cover shadow fade (ms)',
          tooltip: 'Fade-in when entering building, painted, or tree cover shadow (default 3s).',
        },
        easingIn: {
          type: 'dropdown',
          options: easingOptions,
          default: 'smooth',
          label: 'Easing in',
        },
        easingOut: {
          type: 'dropdown',
          options: easingOptions,
          default: 'easeOut',
          label: 'Easing out',
        },
        eyeAdaptationEnabled: {
          type: 'boolean',
          default: true,
          label: 'Eye adaptation',
          tooltip: 'After each layer settles, its offset fades toward neutral (like pupils adjusting). Indoor/outdoor uses the longer time; cover shadows use the shorter time when leaving shadow.',
        },
        eyeAdaptationSec: {
          type: 'slider',
          min: 10,
          max: 180,
          step: 5,
          default: 60,
          label: 'Indoor/outdoor adapt (s)',
          tooltip: 'Eye adaptation for indoor↔outdoor base grade and cloud/canopy modifiers.',
        },
        coverShadowEyeAdaptationSec: {
          type: 'slider',
          min: 1,
          max: 120,
          step: 1,
          default: 3,
          label: 'Cover shadow adapt (s)',
          tooltip: 'Fade in/out for building, painted, and tree cover shadow (default 3s).',
        },
        eyeAdaptationEasing: {
          type: 'dropdown',
          options: easingOptions,
          default: 'easeOut',
          label: 'Adaptation easing',
        },

        dramaEnabled: {
          type: 'boolean',
          default: true,
          label: 'Drama enabled',
          tooltip: 'Bright dazzle when stepping from indoor to outdoor in daylight. Does not run at night, when selecting a token already outdoors, or without an indoor→outdoor walk.',
        },
        dramaRequireDaylight: {
          type: 'boolean',
          default: true,
          label: 'Daylight only',
          tooltip: 'Doorway dazzle only during calendar day phase with day weight above the Environment modifiers day threshold.',
        },
        dramaStrength: {
          type: 'slider',
          min: 0,
          max: 1.5,
          step: 0.01,
          default: 1,
          label: 'Drama strength',
        },
        dramaPeakExposure: {
          type: 'slider',
          min: 0,
          max: 1.5,
          step: 0.01,
          default: 0.75,
          label: 'Peak exposure boost',
          tooltip: 'Extra exposure stops at the dazzle peak (pow2 in shader).',
        },
        dramaPeakBrightness: {
          type: 'slider',
          min: 0,
          max: 0.5,
          step: 0.01,
          default: 0.04,
          label: 'Peak brightness',
          tooltip: 'Prefer exposure for doorway dazzle; brightness lifts mids and can wash the scene pale.',
        },
        dramaPeakSaturation: {
          type: 'slider',
          min: 0,
          max: 0.5,
          step: 0.01,
          default: 0.12,
          label: 'Peak saturation',
        },
        dramaPeakVibrance: {
          type: 'slider',
          min: 0,
          max: 0.5,
          step: 0.01,
          default: 0.14,
          label: 'Peak vibrance',
        },
        dramaPeakVignetteLift: {
          type: 'slider',
          min: 0,
          max: 0.35,
          step: 0.01,
          default: 0.1,
          label: 'Peak vignette lift',
          tooltip: 'Temporarily reduces edge darkening during outdoor doorway dazzle (negative vignette bump).',
        },
        dramaPeakAt: {
          type: 'slider',
          min: 0.05,
          max: 0.75,
          step: 0.01,
          default: 0.3,
          label: 'Peak timing',
          tooltip: 'When in the transition the dazzle peaks (0 = start, 1 = end).',
        },
        dramaPeakWidth: {
          type: 'slider',
          min: 0.08,
          max: 0.5,
          step: 0.01,
          default: 0.26,
          label: 'Peak width',
          tooltip: 'How long the bright punch lingers.',
        },
        dramaSettleDelay: {
          type: 'slider',
          min: 0,
          max: 0.85,
          step: 0.01,
          default: 0.38,
          label: 'Settle delay',
          tooltip: 'Hold at the start grade until this fraction, then ease toward the target.',
        },
        dramaSettleEasing: {
          type: 'dropdown',
          options: easingOptions,
          default: 'easeOut',
          label: 'Settle easing',
        },

        ...outdoorPack,
        outdoorFadeInMs: {
          type: 'slider',
          min: 0,
          max: 10000,
          step: 50,
          default: 0,
          label: 'Outdoor fade in override (ms)',
          tooltip: '0 = use global fade in.',
        },
        outdoorFadeOutMs: {
          type: 'slider',
          min: 0,
          max: 15000,
          step: 50,
          default: 0,
          label: 'Outdoor fade out override (ms)',
          tooltip: '0 = use global fade out.',
        },
        outdoorEasingIn: {
          type: 'dropdown',
          options: { '': '(global)', ...easingOptions },
          default: '',
          label: 'Outdoor easing in',
        },
        outdoorEasingOut: {
          type: 'dropdown',
          options: { '': '(global)', ...easingOptions },
          default: '',
          label: 'Outdoor easing out',
        },

        ...indoorPack,
        indoorFadeInMs: {
          type: 'slider',
          min: 0,
          max: 10000,
          step: 50,
          default: 0,
          label: 'Indoor fade in override (ms)',
          tooltip: '0 = use global fade in.',
        },
        indoorFadeOutMs: {
          type: 'slider',
          min: 0,
          max: 15000,
          step: 50,
          default: 0,
          label: 'Indoor fade out override (ms)',
          tooltip: '0 = use global fade out.',
        },
        indoorEasingIn: {
          type: 'dropdown',
          options: { '': '(global)', ...easingOptions },
          default: '',
          label: 'Indoor easing in',
        },
        indoorEasingOut: {
          type: 'dropdown',
          options: { '': '(global)', ...easingOptions },
          default: '',
          label: 'Indoor easing out',
        },

        envModifiersEnabled: {
          type: 'boolean',
          default: true,
          label: 'Env modifiers enabled',
          tooltip: 'Global weather/time/darkness CC bias (Tier 1).',
        },
        envModifiersLerpMs: {
          type: 'slider',
          min: 50,
          max: 2000,
          step: 10,
          default: 250,
          label: 'Env lerp (ms)',
        },
        envStormThreshold: { type: 'slider', min: 0.2, max: 0.9, step: 0.01, default: 0.55, label: 'Storm threshold' },
        envOvercastThreshold: { type: 'slider', min: 0.1, max: 0.7, step: 0.01, default: 0.35, label: 'Overcast threshold' },
        envClearThreshold: { type: 'slider', min: 0, max: 0.4, step: 0.01, default: 0.18, label: 'Clear threshold' },
        envNightThreshold: { type: 'slider', min: 0, max: 0.5, step: 0.01, default: 0.22, label: 'Night threshold' },
        envDayThreshold: { type: 'slider', min: 0.4, max: 0.9, step: 0.01, default: 0.62, label: 'Day threshold' },
        envDarknessHeavyThreshold: { type: 'slider', min: 0.4, max: 1, step: 0.01, default: 0.72, label: 'Heavy darkness threshold' },
        envDarknessNormalThreshold: { type: 'slider', min: 0.2, max: 0.8, step: 0.01, default: 0.55, label: 'Normal darkness threshold' },

        cloudShadowThresholdLow: { type: 'slider', min: 0, max: 0.8, step: 0.01, default: 0.42, label: 'Cloud shadow low' },
        cloudShadowThresholdHigh: { type: 'slider', min: 0.2, max: 1, step: 0.01, default: 0.62, label: 'Cloud shadow high' },
        canopyShadedThreshold: { type: 'slider', min: 0, max: 0.8, step: 0.01, default: 0.38, label: 'Canopy shaded threshold' },
        canopyOpenThreshold: { type: 'slider', min: 0.2, max: 1, step: 0.01, default: 0.58, label: 'Canopy open threshold' },
        modOutdoorOvercastWeight: { type: 'slider', min: 0, max: 1.5, step: 0.01, default: 1, label: 'Outdoor overcast weight' },
        modCloudShadowWeight: { type: 'slider', min: 0, max: 1.5, step: 0.01, default: 1, label: 'Cloud shadow weight' },
        modCanopyWeight: { type: 'slider', min: 0, max: 1.5, step: 0.01, default: 1, label: 'Canopy weight' },
        modWindowLitBlend: { type: 'slider', min: 0, max: 1, step: 0.01, default: 0.65, label: 'Window-lit blend' },
        buildingShadowSensitivity: {
          type: 'slider',
          min: 0,
          max: 100,
          step: 1,
          default: 75,
          label: 'Building shadow sensitivity',
          tooltip: 'Higher = triggers on lighter partial shadow. Maps to the sunlit cutoff used when classifying building shadow at the token.',
        },
        buildingShadowProbeFootprint: {
          type: 'slider',
          min: 0.25,
          max: 2.5,
          step: 0.05,
          default: 1,
          label: 'Token footprint scale',
          tooltip: 'Sample center + edges/corners of the token. Higher = wider area (helps when the token straddles shadow edges). Darkest reading wins.',
        },
        buildingShadowPartialDetect: {
          type: 'boolean',
          default: true,
          label: 'Partial shadow detect',
          tooltip: 'When enabled, penumbra (soft partial shadow) counts as in shadow, not only deep umbra.',
        },
        buildingShadowUseAdvancedThresholds: {
          type: 'boolean',
          default: false,
          label: 'Manual lit thresholds',
          tooltip: 'Use Building shadow lit low/high below instead of the sensitivity slider.',
        },
        buildingShadowLitLow: {
          type: 'slider',
          min: 0.2,
          max: 0.99,
          step: 0.01,
          default: 0.88,
          label: 'Building shadow lit low',
          tooltip: 'Advanced only. Lit factor (R) at or below → definite shadow.',
        },
        buildingShadowLitHigh: {
          type: 'slider',
          min: 0.3,
          max: 1,
          step: 0.01,
          default: 0.94,
          label: 'Building shadow lit high',
          tooltip: 'Advanced only. Lit at or above → full sunlit (leave building shadow).',
        },
        paintedShadowLitLow: { type: 'slider', min: 0.3, max: 0.99, step: 0.01, default: 0.85, label: 'Painted shadow lit low' },
        paintedShadowLitHigh: { type: 'slider', min: 0.4, max: 1, step: 0.01, default: 0.94, label: 'Painted shadow lit high' },
        treeShadowLitLow: { type: 'slider', min: 0.7, max: 0.99, step: 0.01, default: 0.93, label: 'Tree shadow lit low', tooltip: 'Vegetation billboard lit factor at or below → tree dapple (soft canopy; higher = more sensitive).' },
        treeShadowLitHigh: { type: 'slider', min: 0.75, max: 1, step: 0.01, default: 0.98, label: 'Tree shadow lit high' },
        treeDappleDayThreshold: { type: 'slider', min: 0.1, max: 0.9, step: 0.01, default: 0.35, label: 'Tree dapple day weight', tooltip: 'Calendar day weight must reach this for tree dapple.' },
        modBuildingShadowWeight: { type: 'slider', min: 0, max: 1.5, step: 0.01, default: 1, label: 'Building shadow weight' },
        modPaintedShadowWeight: { type: 'slider', min: 0, max: 1.5, step: 0.01, default: 1, label: 'Painted shadow weight' },
        modTreeDappleWeight: { type: 'slider', min: 0, max: 1.5, step: 0.01, default: 1, label: 'Tree dapple weight' },
        modTreeDappleStrength: { type: 'slider', min: 0, max: 1.5, step: 0.01, default: 0.72, label: 'Tree dapple shader strength', tooltip: 'Procedural leaf-noise intensity in Color Correction.' },
        modTreeDappleScale: { type: 'slider', min: 8, max: 120, step: 1, default: 42, label: 'Tree dapple cell scale' },
        modTreeDappleGreenR: { type: 'slider', min: 0.5, max: 1.2, step: 0.01, default: 0.86, label: 'Tree dapple green R' },
        modTreeDappleGreenG: { type: 'slider', min: 0.5, max: 1.4, step: 0.01, default: 1.06, label: 'Tree dapple green G' },
        modTreeDappleGreenB: { type: 'slider', min: 0.5, max: 1.2, step: 0.01, default: 0.82, label: 'Tree dapple green B' },

        coherenceEnabled: { type: 'boolean', default: true, label: 'Coherence enabled' },
        coherenceAtmosphereScale: { type: 'slider', min: 0, max: 1, step: 0.01, default: 0.6, label: 'Atmosphere coupling' },
        coherenceMaxExposure: { type: 'slider', min: 0.5, max: 2, step: 0.01, default: 1.35, label: 'Max context exposure' },
        contextVignetteInner: {
          type: 'slider',
          min: 0.1,
          max: 1.2,
          step: 0.01,
          default: 0.42,
          label: 'Inner radius',
          tooltip: 'Normalized radial distance where contextual vignette falloff begins (0 = center, 1 = edge). Lower = tighter vignette.',
        },
        contextVignetteSoftness: {
          type: 'slider',
          min: 0.05,
          max: 1.2,
          step: 0.01,
          default: 0.55,
          label: 'Falloff width',
          tooltip: 'How gradually the contextual vignette darkens from inner radius to screen edge.',
        },
        coherenceMaxVignette: {
          type: 'slider',
          min: 0.1,
          max: 1,
          step: 0.01,
          default: 0.55,
          label: 'Max vignette strength',
          tooltip: 'Safety clamp on stacked vignette from all active triggers.',
        },
        dazzleContextGradeGate: { type: 'slider', min: 0, max: 1, step: 0.01, default: 0.45, label: 'Dazzle gate during drama' },
        contextSpatialEnabled: { type: 'boolean', default: true, label: 'Spatial context blend' },
        contextSpatialStrength: { type: 'slider', min: 0, max: 1, step: 0.01, default: 0.72, label: 'Spatial blend strength' },

        ...envOvercastPack,
        ...envStormPack,
        ...envNightPack,
        ...envTwilightPack,
        ...envDarknessPack,
        ...modOutdoorOvercastPack,
        ...modCloudShadowPack,
        ...modCanopyPack,
        ...modWindowLitPack,
        ...modBuildingShadowPack,
        ...modPaintedShadowPack,
        ...modTreeDapplePack,

        statusSubject: { type: 'string', default: '(none)', label: 'Subject token', readonly: true },
        statusProbeAge: { type: 'string', default: '—', label: 'Last probe age', readonly: true },
        statusOutdoorsSample: { type: 'string', default: '—', label: 'Outdoors sample', readonly: true },
        statusIndoorOutdoor: { type: 'string', default: 'Unknown', label: 'Indoor / Outdoor', readonly: true },
        statusState: { type: 'string', default: 'Idle', label: 'Transition', readonly: true },
        statusMaskProbe: { type: 'string', default: '—', label: 'Mask probe', readonly: true },
        statusCcOverlay: { type: 'string', default: 'Off', label: 'CC overlay', readonly: true },
        statusSkyCondition: { type: 'string', default: '—', label: 'Sky condition', readonly: true },
        statusDayPhase: { type: 'string', default: '—', label: 'Day phase', readonly: true },
        statusContextKey: {
          type: 'string',
          default: '—',
          label: 'Context key',
          readonly: true,
          multiline: true,
          rows: 6,
          tooltip: 'One active trigger per line (indoor/outdoor, env, cloud, canopy, cover shadow, etc.).',
        },
        statusCoverShadow: { type: 'string', default: '—', label: 'Cover shadow', readonly: true },
        statusEyeAdaptation: { type: 'string', default: '—', label: 'Eye adaptation', readonly: true },
      },
      presets: {
        Neutral: {
          enabled: false,
          dramaEnabled: false,
          envModifiersEnabled: false,
          outdoorExposure: 0,
          outdoorSaturation: 0,
          indoorExposure: 0,
          indoorSaturation: 0,
          indoorVignetteStrength: 0,
        },
        Extreme: buildIntensityPreset(1.38),
        Cinematic: buildIntensityPreset(1),
        Moderate: buildIntensityPreset(0.58),
        Mild: buildIntensityPreset(0.3),
      },
    };
  }
}
