/**
 * MACHINE-HARVESTED from legacy/compositor-v2/effects/DistortionManager.js (V2 class DistortionManager), 2026-07-17.
 * Generated by tools/harvest-params.mjs — see that file for the transform rules.
 * Do not hand-edit the `SCHEMA`/`GROUPS` exports; re-run the harvest instead.
 */
export const SOURCE_CLASS = 'DistortionManager';
export const SOURCE_FILE = 'legacy/compositor-v2/effects/DistortionManager.js';
export const GROUPS = [
  {
    name: 'global',
    label: 'Global Settings',
    type: 'inline',
    parameters: ['globalIntensity'],
  },
  {
    name: 'debug',
    label: 'Debug',
    type: 'inline',
    advanced: true,
    collapsed: true,
    parameters: ['debugMode', 'debugShowMask', 'debugShowWaterShoreBand'],
  },
];
export const SCHEMA = {
  enabled: {
    type: 'bool',
    default: true,
    label: 'enabled',
  },
  globalIntensity: {
    type: 'float',
    default: 2,
    min: 0,
    max: 2,
    step: 0.01,
    label: 'Global Intensity',
  },
  debugMode: {
    type: 'bool',
    default: false,
    label: 'Debug Mode',
  },
  debugShowMask: {
    type: 'bool',
    default: false,
    label: 'Show Distortion Mask',
  },
  debugShowWaterShoreBand: {
    type: 'bool',
    default: false,
    label: 'Show Water Shore Band',
  },
};
