/**
 * MACHINE-HARVESTED from legacy/compositor-v2/effects/HalftoneEffectV2.js (V2 class HalftoneEffectV2), 2026-07-17.
 * Generated by tools/harvest-params.mjs — see that file for the transform rules.
 * Do not hand-edit the `SCHEMA`/`GROUPS` exports; re-run the harvest instead.
 */
export const SOURCE_CLASS = 'HalftoneEffectV2';
export const SOURCE_FILE = 'legacy/compositor-v2/effects/HalftoneEffectV2.js';
export const GROUPS = [
  {
    name: 'look',
    label: 'Look',
    type: 'folder',
    expanded: true,
    parameters: ['strength', 'radius', 'shape'],
  },
  {
    name: 'mix',
    label: 'Mix',
    type: 'folder',
    advanced: true,
    expanded: true,
    parameters: ['blendingMode', 'scatter'],
  },
  {
    name: 'output',
    label: 'Output',
    type: 'folder',
    advanced: true,
    expanded: false,
    parameters: ['greyscale'],
  },
];
export const SCHEMA = {
  enabled: {
    type: 'bool',
    default: false,
    label: 'enabled',
  },
  strength: {
    type: 'float',
    default: 0.47,
    min: 0,
    max: 1,
    step: 0.01,
    label: 'Strength',
    help: 'Intensity of the halftone treatment (0 leaves the image unchanged in the shader).',
  },
  radius: {
    type: 'float',
    default: 6.3,
    min: 1,
    max: 16,
    step: 0.25,
    label: 'Radius',
    help: 'Cell size in pixels (coarser halftone as this increases).',
  },
  shape: {
    type: 'enum',
    default: 1,
    values: [1, 2, 3, 4],
    valueLabels: {
      1: 'Dot',
      2: 'Ellipse',
      3: 'Line',
      4: 'Square',
    },
    label: 'Shape',
    help: 'Geometry of each halftone spot.',
  },
  blendingMode: {
    type: 'enum',
    default: 1,
    values: [1, 2, 3, 4, 5],
    valueLabels: {
      1: 'Linear',
      2: 'Multiply',
      3: 'Add',
      4: 'Lighter',
      5: 'Darker',
    },
    label: 'Blend mode',
    help: 'Compositing mode between source and halftone.',
  },
  scatter: {
    type: 'float',
    default: 0,
    min: 0,
    max: 2,
    step: 0.01,
    label: 'Scatter',
    help: 'Random displacement of the halftone grid for an imperfect print feel.',
  },
  greyscale: {
    type: 'bool',
    default: false,
    label: 'Greyscale',
    help: 'Halftone from luminance only (monochrome output).',
  },
};
