/**
 * MACHINE-HARVESTED from legacy/compositor-v2/effects/PrismEffectV2.js (V2 class PrismEffectV2), 2026-07-17.
 * Generated by tools/harvest-params.mjs — see that file for the transform rules.
 * Do not hand-edit the `SCHEMA`/`GROUPS` exports; re-run the harvest instead.
 */
export const SOURCE_CLASS = 'PrismEffectV2';
export const SOURCE_FILE = 'legacy/compositor-v2/effects/PrismEffectV2.js';
export const GROUPS = [
  {
    name: 'mask-status-prism',
    type: 'mask-status',
    parameters: [],
  },
  {
    name: 'refraction',
    label: 'Refraction',
    type: 'folder',
    parameters: ['intensity', 'spread', 'brightness', 'opacity', 'maskThreshold'],
  },
  {
    name: 'facets',
    label: 'Crystal Facets',
    type: 'folder',
    advanced: true,
    parameters: ['facetScale', 'facetAnimate', 'facetSpeed', 'facetSoftness'],
  },
  {
    name: 'parallax',
    label: 'Camera Parallax',
    type: 'inline',
    advanced: true,
    parameters: ['parallaxStrength'],
  },
  {
    name: 'glint',
    label: 'Surface Glint',
    type: 'folder',
    advanced: true,
    parameters: ['glintStrength', 'glintThreshold'],
  },
];
export const SCHEMA = {
  intensity: {
    type: 'float',
    default: 0.3,
    min: 0,
    max: 5,
    step: 0.1,
    label: 'Distortion',
  },
  spread: {
    type: 'float',
    default: 0.6,
    min: 0,
    max: 1,
    step: 0.1,
    label: 'Spectral Spread',
  },
  brightness: {
    type: 'float',
    default: 1.5,
    min: 0.5,
    max: 3,
    step: 0.1,
    label: 'Brightness Boost',
  },
  opacity: {
    type: 'float',
    default: 0.25,
    min: 0,
    max: 1,
    step: 0.05,
    label: 'Opacity',
  },
  maskThreshold: {
    type: 'float',
    default: 0.9,
    min: 0,
    max: 1,
    step: 0.01,
    label: 'Mask Brightness Cutoff',
  },
  facetScale: {
    type: 'int',
    default: 254,
    min: 1,
    max: 1000,
    step: 1,
    label: 'Facet Scale',
  },
  facetAnimate: {
    type: 'bool',
    default: true,
    label: 'Animate Facets',
  },
  facetSpeed: {
    type: 'float',
    default: 1.01,
    min: 0,
    max: 2,
    step: 0.01,
    label: 'Animation Speed',
  },
  facetSoftness: {
    type: 'float',
    default: 0.85,
    min: 0,
    max: 1,
    step: 0.01,
    label: 'Facet Softness',
  },
  parallaxStrength: {
    type: 'float',
    default: 2.4,
    min: 0,
    max: 5,
    step: 0.05,
    label: 'Parallax Strength',
  },
  glintStrength: {
    type: 'float',
    default: 0.4,
    min: 0,
    max: 2,
    step: 0.05,
    label: 'Glint Strength',
  },
  glintThreshold: {
    type: 'float',
    default: 0.13,
    min: 0,
    max: 0.99,
    step: 0.01,
    label: 'Glint Sharpness',
  },
};
