/**
 * MACHINE-HARVESTED from legacy/compositor-v2/effects/SepiaEffectV2.js (V2 class SepiaEffectV2), 2026-07-17.
 * Generated by tools/harvest-params.mjs — see that file for the transform rules.
 * Do not hand-edit the `SCHEMA`/`GROUPS` exports; re-run the harvest instead.
 */
export const SOURCE_CLASS = 'SepiaEffectV2';
export const SOURCE_FILE = 'legacy/compositor-v2/effects/SepiaEffectV2.js';
export const GROUPS = [
  {
    name: 'look',
    label: 'Look',
    type: 'folder',
    expanded: true,
    parameters: ['strength'],
  },
];
export const SCHEMA = {
  enabled: {
    type: 'bool',
    default: true,
    label: 'enabled',
  },
  strength: {
    type: 'float',
    default: 0.6,
    min: 0,
    max: 1,
    step: 0.01,
    label: 'Strength',
    help: 'How much sepia is mixed in (0 leaves the image unchanged).',
  },
};
