/**
 * MACHINE-HARVESTED from legacy/compositor-v2/effects/SharpenEffectV2.js (V2 class SharpenEffectV2), 2026-07-17.
 * Generated by tools/harvest-params.mjs — see that file for the transform rules.
 * Do not hand-edit the `SCHEMA`/`GROUPS` exports; re-run the harvest instead.
 */
export const SOURCE_CLASS = 'SharpenEffectV2';
export const SOURCE_FILE = 'legacy/compositor-v2/effects/SharpenEffectV2.js';
export const GROUPS = [
  {
    name: 'look',
    label: 'Look',
    type: 'folder',
    expanded: true,
    parameters: ['amount', 'radiusPx', 'threshold'],
  },
];
export const SCHEMA = {
  enabled: {
    type: 'bool',
    default: false,
    label: 'enabled',
  },
  amount: {
    type: 'float',
    default: 0.5,
    min: 0,
    max: 2,
    step: 0.01,
    label: 'Amount',
    help: 'Strength of the sharpen blend (0 = no effect).',
  },
  radiusPx: {
    type: 'float',
    default: 2,
    min: 0,
    max: 6,
    step: 0.1,
    label: 'Radius (px)',
    help: 'Blur radius in pixels used for the unsharp mask.',
  },
  threshold: {
    type: 'float',
    default: 0,
    min: 0,
    max: 0.25,
    step: 0.005,
    label: 'Threshold',
    help: 'Ignore weak edges below this luma delta to limit noise sharpening.',
  },
};
